### ISSUE TITLE
WebSearch: filter non-existing collections in RestrictedCollectionDataCacher

### ISSUE THREAD

**Issue by jeromecaffaro** [inveniosoftware/invenio#1122]
Originally on 2012-07-26

Function `search_engine.RestrictedCollectionDataCacher.cache_filler()` precomputes a list of restricted collections based on existing WebAccess authorizations (parameter 'collection' of 'viewrestcoll' action). In case an authorization is set for a non existing collection (for eg. with demo role 'thesescurator' still connected to collection 'Theses' on a site where 'Theses' collection has been removed) the cache will contain this non-existing collection. Exceptions might arise if the caller expects the returned list to only contain "valid" collections.

A sample traceback is included further below, occurring when a user (not super-admin) is trying to access a record that has not yet been "assigned" to a collection.

`search_engine.RestrictedCollectionDataCacher.cache_filler()` could be enhanced to only consider "valid" collections, or "callers" of the cache should be made aware about the inclusion of possible non-existing collections.

(Of course anyone affected by this behaviour could remove the unnecessary authorizations from the WebAccess admin interface in the meantime)

-Sample traceback:*
```
* 2012-07-26 14:48:50 -> KeyError: 'foo' (search_engine.py:390:get_collection_reclist)

-* User details
                                     agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:14.0) Gecko/20100101 Firefox/14.0.1
                                     email: guest
                                     group: []
                                     guest: 1
                                  nickname: 
            precached_canseehiddenmarctags: False
precached_permitted_restricted_collections: []
                        precached_useadmin: False
                       precached_usealerts: False
                      precached_useapprove: False
                      precached_usebaskets: False
                       precached_usegroups: False
                        precached_useloans: False
                     precached_usemessages: False
             precached_usepaperattribution: False
                   precached_usepaperclaim: False
                        precached_usestats: False
                   precached_viewclaimlink: False
                 precached_viewsubmissions: False
                                   referer: <>
                               remote_host: 
                                 remote_ip: 127.0.0.1
                                   session: 80808080808080808080808080
                                       uid: 0
                                       uri: </record/121?>

-* Traceback details 

Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/invenio/webinterface_handler.py", line 413, in _handler
    return root._traverse(req, path, False, guest_p)
  File "/usr/lib/python2.6/dist-packages/invenio/webinterface_handler.py", line 250, in _traverse
    result = _check_result(req, obj(req, form))
  File "/usr/lib/python2.6/dist-packages/invenio/websearch_webinterface.py", line 1035, in __call__
    (auth_code, auth_msg) = check_user_can_view_record(user_info, self.recid)
  File "/usr/lib/python2.6/dist-packages/invenio/search_engine.py", line 292, in check_user_can_view_record
    restricted_collections = get_restricted_collections_for_recid(recid, recreate_cache_if_needed=False)
  File "/usr/lib/python2.6/dist-packages/invenio/search_engine.py", line 241, in get_restricted_collections_for_recid
    return [collection for collection in restricted_collection_cache.cache if recid in get_collection_reclist(collection, recreate_cache_if_needed=False)]
  File "/usr/lib/python2.6/dist-packages/invenio/search_engine.py", line 390, in get_collection_reclist
    if not collection_reclist_cache.cache[coll]:
KeyError: 'foo'

-* Stack frame details

Frame application in /usr/lib/python2.6/dist-packages/invenio/webinterface_handler_wsgi.py at line 462
-------------------------------------------------------------------------------
       459                 else:
       460                     ret = invenio_handler(req)
       461             else:
---->  462                 ret = invenio_handler(req)
       463             req.flush()
       464         except SERVER_RETURN, status:
       465             status = int(str(status))
-------------------------------------------------------------------------------
	      start_response =  '<built-in method start_response of mod_wsgi.Adapter object at 0x2467d890>'
	             environ =  "{'mod_wsgi.listener_port': '80', 'HTTP_COOKIE': 'INVENIOSESSIONstub=NO; INVENIOSESSION=c22f4168e416de92c9a9a917635e90c8', 'mod_wsgi.listener_host': *, 'SERVER_SOFTWARE': 'Apache/2.2.17 (Ubuntu)', 'SCRIPT_NAME': *, 'mod_wsgi.handler_script': *, 'SERVER_SIGNATURE': '<address>Apache/2.2.17 (Ubuntu) Server at invenio-demo.cern.ch Port 80</address>\\n', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/record/121', 'SERVER_PROTOCOL': 'HTTP/1.1', 'QUERY_STRING': *, 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu;  [...]
	                 req =  '<invenio.webinterface_handler_wsgi.SimulatedModPythonRequest object at 0x246619cc>'
	    possible_handler =  'None'
	     possible_module =  'None'

Frame _profiler in /usr/lib/python2.6/dist-packages/invenio/webinterface_handler.py at line 360
-------------------------------------------------------------------------------
       357                     raise Exception('Debugging requested, but no debugger registered: "%s"' % args['debug'])
       358             return _handler(req)
       359         else:
---->  360             return _handler(req)
       361 
       362     def _handler(req):
       363         """ This handler is invoked by mod_python with the apache request."""
-------------------------------------------------------------------------------
	            _handler =  '<function _handler at 0x2465a87c>'
	                args =  '{}'
	                 req =  '<invenio.webinterface_handler_wsgi.SimulatedModPythonRequest object at 0x246619cc>'

Frame _handler in /usr/lib/python2.6/dist-packages/invenio/webinterface_handler.py at line 434
-------------------------------------------------------------------------------
       431                         args = cgi.parse_qs(req.args)
       432                         if 'debug' in args:
       433                             remote_debugger.error_msg(args['debug'])
---->  434                 register_exception(req=req, alert_admin=True)
       435                 raise
       436 
       437             # Serve an error by default.
-------------------------------------------------------------------------------
	     allowed_methods =  "('GET', 'POST', 'HEAD', 'OPTIONS')"
	             guest_p =  '1'
	                 req =  '<invenio.webinterface_handler_wsgi.SimulatedModPythonRequest object at 0x246619cc>'
	                 uri =  "'/record/121'"
	                path =  "['record', '121']"
	                root =  '<invenio.webinterface_layout.WebInterfaceInvenio object at 0x2465b14c>'

Frame _traverse in /usr/lib/python2.6/dist-packages/invenio/webinterface_handler.py at line 250
-------------------------------------------------------------------------------
       247                 req.uri not in CFG_NO_LANG_RECOGNITION_URIS:
       248             ln = get_preferred_user_language(req)
       249             form.add_field('ln', ln)
---->  250         result = _check_result(req, obj(req, form))
       251         return result
       252 
       253     def __call__(self, req, form):
-------------------------------------------------------------------------------
	                 obj =  '<invenio.websearch_webinterface.WebInterfaceRecordPages object at 0x246f1eec>'
	                name =  'None'
	                form =  "{'ln': [Field('ln', 'fr')]}"
	                  ln =  "'fr'"
	             guest_p =  '1'
	                 req =  '<invenio.webinterface_handler_wsgi.SimulatedModPythonRequest object at 0x246619cc>'
	           component =  "'record'"
	             do_head =  'False'
	                path =  '[]'
	                self =  '<invenio.webinterface_layout.WebInterfaceInvenio object at 0x2465b14c>'

Frame __call__ in /usr/lib/python2.6/dist-packages/invenio/websearch_webinterface.py at line 1035
-------------------------------------------------------------------------------
      1032                 pass
      1033 
      1034         user_info = collect_user_info(req)
----> 1035         (auth_code, auth_msg) = check_user_can_view_record(user_info, self.recid)
      1036 
      1037         if argd['rg'] > CFG_WEBSEARCH_MAX_RECORDS_IN_GROUPS and acc_authorize_action(req, 'runbibedit')[0] != 0:
      1038             argd['rg'] = CFG_WEBSEARCH_MAX_RECORDS_IN_GROUPS
-------------------------------------------------------------------------------
	                 uid =  '0'
	                form =  "{'ln': [Field('ln', 'fr')]}"
	                self =  '<invenio.websearch_webinterface.WebInterfaceRecordPages object at 0x246f1eec>'
	                 req =  '<invenio.webinterface_handler_wsgi.SimulatedModPythonRequest object at 0x246619cc>'
	           user_info =  "{'uid': 0, 'agent': 'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:14.0) Gecko/20100101 Firefox/14.0.1', 'precached_viewclaimlink': False, 'session': '80808080808080808080808080', 'precached_useadmin': False, 'group': [], 'guest': '1', 'precached_usepaperattribution': False, 'precached_usepaperclaim': False, 'precached_viewsubmissions': False, 'precached_usegroups': False, 'email': 'guest', 'precached_usealerts': False, 'precached_usestats': False, 'precached_usemessages': False, 'referer': '' [...]
	                argd =  "{'f1': *, 'f2': *, 'f3': *, 'op1': *, 'op2': *, 'cc': 'Atlantis Institute of Fictive Science', 'ec': [], 'ap': 1, 'tab': *, 'd2': *, 'id': -1, 'd1': *, 'd2y': 0, 'sysnb': *, 'jrec': 0, 'ln': 'fr', 'sysno': *, 'rg': 10, 'm1': *, 'm3': *, 'm2': *, 'd2m': 0, 'd2d': 0, 'wl': 50000, 'action': 'search', 'rm': *, 'verbose': 0, 'dt': *, 'p2': *, 'p3': *, 'c': [], 'p1': *, 'so': 'd', 'f': *, 'of': 'hb', 'sp': *, 'd1y': 0, 'd1d': 0, 'p': '', 'recid': 121, 'aas': 0, 'recidb': -1, 'sc': [...]

Frame check_user_can_view_record in /usr/lib/python2.6/dist-packages/invenio/search_engine.py at line 292
-------------------------------------------------------------------------------
       289     if is_user_owner_of_record(user_info, recid):
       290         ## Perfect! It's authorized then!
       291         return (0, '')
---->  292     restricted_collections = get_restricted_collections_for_recid(recid, recreate_cache_if_needed=False)
       293     if restricted_collections:
       294         ## If there are restricted collections the user must be authorized to all/any of them (depending on the policy)
       295         auth_code, auth_msg = 0, ''
-------------------------------------------------------------------------------
	              policy =  "'ALL'"
	           user_info =  "{'uid': 0, 'agent': 'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:14.0) Gecko/20100101 Firefox/14.0.1', 'precached_viewclaimlink': False, 'session': '80808080808080808080808080', 'precached_useadmin': False, 'group': [], 'guest': '1', 'precached_usepaperattribution': False, 'precached_usepaperclaim': False, 'precached_viewsubmissions': False, 'precached_usegroups': False, 'email': 'guest', 'precached_usealerts': False, 'precached_usestats': False, 'precached_usemessages': False, 'referer': '' [...]
	               recid =  '121'

Frame get_restricted_collections_for_recid in /usr/lib/python2.6/dist-packages/invenio/search_engine.py at line 241
-------------------------------------------------------------------------------
       238     if recreate_cache_if_needed:
       239         restricted_collection_cache.recreate_cache_if_needed()
       240         collection_reclist_cache.recreate_cache_if_needed()
---->  241     return [collection for collection in restricted_collection_cache.cache if recid in get_collection_reclist(collection, recreate_cache_if_needed=False)]
       242 
       243 def is_user_owner_of_record(user_info, recid):
       244     """
-------------------------------------------------------------------------------
	                _[1] =  '[]'
	recreate_cache_if_needed =  'False'
	               recid =  '121'
	          collection =  "'foo'"

Frame get_collection_reclist in /usr/lib/python2.6/dist-packages/invenio/search_engine.py at line 390
-------------------------------------------------------------------------------
       387     """Return hitset of recIDs that belong to the collection 'coll'."""
       388     if recreate_cache_if_needed:
       389         collection_reclist_cache.recreate_cache_if_needed()
---->  390     if not collection_reclist_cache.cache[coll]:
       391         # not yet it the cache, so calculate it and fill the cache:
       392         set = intbitset()
       393         query = "SELECT nbrecs,reclist FROM collection WHERE name=%s"
-------------------------------------------------------------------------------
	recreate_cache_if_needed =  'False'
	                coll =  "'foo'"
```

**Comment by jirikuncar** [comment]
Refactored in v2.0.0.
