### ISSUE TITLE
installation: upgrade problem with invenio_2012_11_27_new_selfcite_tables

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#1256]
Originally on 2013-01-16

While running the upgrader in Inveniocfg on invenio_2012_11_27_new_selfcite_tables, the following error happens if the tables are already created:

```
$ inveniocfg --upgrade --yes-i-know
>>> Following upgrade(s) will be applied:
>>>  * invenio_2012_11_27_new_selfcite_tables (New selfcite tables)
>>>  * invenio_2012_10_31_tablesorter_location (Standardisation of the jQuery tablesorter location)
>>>  * invenio_2012_12_11_new_citation_errors_table (New rnkCITATIONDATAERR table)
>>> Running pre-upgrade checks...
>>> pre_check_bibsched: Checking bibsched process...
>>> Calculating estimated upgrade time...
>>> Applying invenio_2012_11_27_new_selfcite_tables (New selfcite tables)
Traceback (most recent call last):
  File "/home/jlavik/envs/inspire/bin/inveniocfg", line 33, in <module>
    main()
  File "/home/jlavik/envs/inspire/local/lib/python2.7/site-packages/invenio/inveniocfg.py", line 1564, in main
    cli_cmd_upgrade(conf)
  File "/home/jlavik/envs/inspire/local/lib/python2.7/site-packages/invenio/inveniocfg.py", line 1292, in cli_cmd_upgrade
    cmd_upgrade(conf)
  File "/home/jlavik/envs/inspire/local/lib/python2.7/site-packages/invenio/inveniocfg_upgrader.py", line 900, in cmd_upgrade
    upgrader.apply_upgrade(u)
  File "/home/jlavik/envs/inspire/local/lib/python2.7/site-packages/invenio/inveniocfg_upgrader.py", line 488, in apply_upgrade
    upgrade['do_upgrade']()
  File "/home/jlavik/envs/inspire/lib/python/invenio/upgrades/invenio_2012_11_27_new_selfcite_tables.py", line 50, in do_upgrade
    """)
  File "/home/jlavik/envs/inspire/local/lib/python2.7/site-packages/invenio/dbquery.py", line 202, in run_sql
    rc = cur.execute(sql, param)
  File "/home/jlavik/envs/inspire/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 176, in execute
    if not self._defer_warnings: self._warning_check()
  File "/home/jlavik/envs/inspire/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 85, in _warning_check
    warnings = self._get_db().show_warnings()
  File "/home/jlavik/envs/inspire/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 317, in show_warnings
    self.query("SHOW WARNINGS")
_mysql_exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
Exception _mysql_exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now") in <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0x232a9d0>> ignored
```

I'd suggest to update the upgrading script to first check if the tables are created. Removing or copying the tables fixed the problem locally on my DEV-box, but it is perhaps not a nice alternative on production machines.

**Comment by jirikuncar** [comment]
It looks like it was addressed as part of 92c42da899d0d9fc706b5df8b090fe397e85eb06.

--
cc @inveniosoftware/triagers
