### ISSUE TITLE
BibCirculation: amend web tests

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1412]
Originally on 2013-03-19

BibCirculation web tests need to be amended.

```
$ python ./bibcirculation_web_tests.py --yes-i-know
test_loan_and_return_book (__main__.BibcirculationLoanRequestReturnWebTest) ... Starting test_loan_and_return_book...
Logged in as admin.
In Bibcirculation admin page.
In 'Loan' tab, searching for the borrower.
Found the borrower! Entering the barcode.
ERROR
ERROR
test_purchase_book_request_with_recid (__main__.BibcirculationBookPurchaseWebTest) ... Starting test_purchase_book_request_with_recid...
Reached a detailed record, clicking on purchase link.
ERROR

======================================================================
ERROR: test_loan_and_return_book (__main__.BibcirculationLoanRequestReturnWebTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./bibcirculation_web_tests.py", line 74, in test_loan_and_return_book
    self.fill_textbox("barcode", "bc-34001")
  File "/home/simko/.virtualenvs/invenio-master/local/lib/python2.7/site-packages/invenio/testutils.py", line 869, in fill_textbox
    self.find_element_by_name_with_timeout(textbox_name)
  File "/home/simko/.virtualenvs/invenio-master/local/lib/python2.7/site-packages/invenio/testutils.py", line 535, in find_element_by_name_with_timeout
    raise InvenioWebTestCaseException(element=element_name)
InvenioWebTestCaseException: "Time for finding the element 'barcode' has expired"

======================================================================
ERROR: test_loan_and_return_book (__main__.BibcirculationLoanRequestReturnWebTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/simko/.virtualenvs/invenio-master/local/lib/python2.7/site-packages/invenio/testutils.py", line 519, in tearDown
    self.assertEqual([], self.errors)
AssertionError: Lists differ: [] != ['-1 ## -1', '-1 -1']

Second list contains 2 additional elements.
First extra element 0:
-1 == -1

- []
+ ['-1 ## -1', '-1 -1']

======================================================================
ERROR: test_purchase_book_request_with_recid (__main__.BibcirculationBookPurchaseWebTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./bibcirculation_web_tests.py", line 169, in test_purchase_book_request_with_recid
    self.find_element_by_link_text_with_timeout("Purchase it for me!")
  File "/home/simko/.virtualenvs/invenio-master/local/lib/python2.7/site-packages/invenio/testutils.py", line 551, in find_element_by_link_text_with_timeout
    raise InvenioWebTestCaseException(element=element_link_text)
InvenioWebTestCaseException: "Time for finding the element 'Purchase it for me!' has expired"

----------------------------------------------------------------------
Ran 2 tests in 79.440s

FAILED (errors=3)
```

**Comment by tiborsimko** [comment]
@Kennethhole Have you perhaps touched this during your recent TIND circulation enhancements?

**Comment by audub** [comment]
I'm afraid not, unless @blixhavn did something I don't know about.
