### ISSUE TITLE
BibSched: follow with less exits on interrupt

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#1471]
Originally on 2013-04-16

After using the follow (shift-F) function in less (when looking at logs), one needs to do an interrupt to tell less to not follow anymore. However, this interrupt seems to be propagated to python which naturally exits.

```
Traceback (most recent call last):
  File "/opt/cds-invenio/bin/bibsched", line 33, in ?
    main()
  File "/usr/lib/python2.4/site-packages/invenio/bibsched.py", line 1812, in main
    {'start': start,
  File "/usr/lib/python2.4/site-packages/invenio/bibsched.py", line 1634, in monitor
    Manager(old_stdout)
  File "/usr/lib/python2.4/site-packages/invenio/bibsched.py", line 333, in __init__
    wrapper(self.start)
  File "/usr/lib64/python2.4/curses/wrapper.py", line 44, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python2.4/site-packages/invenio/bibsched.py", line 1020, in start
    self.handle_keys(char)
  File "/usr/lib/python2.4/site-packages/invenio/bibsched.py", line 391, in handle_keys
    self.openlog()
  File "/usr/lib/python2.4/site-packages/invenio/bibsched.py", line 466, in openlog
    raw_input()
KeyboardInterrupt
```

**Comment by tiborsimko** [comment]
@jalavik Is this still applicable?  See also https://github.com/inveniosoftware/invenio/issues/1701
