### ISSUE TITLE
BibDocFile: fix troubles with text file type detection

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1619]
Originally on 2013-11-08

On new SLC6 worker nodes, we have a new problem:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/unittest.py", line 278, in run
    testMethod()
  File "/opt/invenio/lib/python/invenio/bibdocfile_regression_tests.py", line 157, in test_guess_format_from_url_local_gpl_license
    self.assertEqual(guess_format_from_url(local_path), '.txt')
  File "/usr/lib64/python2.6/unittest.py", line 349, in failUnlessEqual
    (msg or '%r != %r' % (first, second))
AssertionError: '.el' != '.txt'
```

How to reproduce:

```
$ sudo -u apache nosetests invenio.bibdocfile_regression_tests:BibDocFileGuessFormat.test_guess_format_from_url_local_gpl_license
F
======================================================================
FAIL: test_guess_format_from_url_local_gpl_license (invenio.bibdocfile_regression_tests.BibDocFileGuessFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/invenio/bibdocfile_regression_tests.py", line 157, in test_guess_format_from_url_local_gpl_license
    self.assertEqual(guess_format_from_url(local_path), '.txt')
AssertionError: '.el' != '.txt'

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (failures=1)
Exception TypeError: "'NoneType' object is not callable" in <bound method Magic.__del__ of <magic.Magic instance at 0x36ab3b0>> ignored
```

Apparently magic things the license text file used in this test case is an Emacs Lisp file...

**Comment by tiborsimko** [comment]
Note: this is known to happen for v1.0.x and v1.1.x on CentOS6.  The `CFG_BIBDOCFILE_PREFERRED_MIMETYPES_MAPPING` was introduced in v1.2.0.
