### ISSUE TITLE
BibDocFile: Document File Manager problem with "revise"

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1620]
Originally by _[switowsk (@switowski)](https://github.com/switowski)_ on 2013-11-08

In the Document File Manager, when user clicks "revise" and changes the name of the file and clicks "Upload" for the first time it works fine. But, when the user clicks "revise", changes the name of the same file again and tries to save it again, the form gets stuck (the spinning icon keeps spinning and the text "Uploading" doesn't disappear, so there is an error).
The typical use case for that can be for example when user makes a typo and wants to correct it before clicking "Apply changes".
The trackback message that I'm getting:

```
Traceback (most recent call last):
  File "/home/switowsk/.virtualenvs/master/lib/python2.7/site-packages/invenio/webinterface_handler.py", line 424, in _handler
    return root._traverse(req, path, False, guest_p)
  File "/home/switowsk/.virtualenvs/master/lib/python2.7/site-packages/invenio/webinterface_handler.py", line 239, in _traverse
    return obj._traverse(req, path, do_head, guest_p)
  File "/home/switowsk/.virtualenvs/master/lib/python2.7/site-packages/invenio/webinterface_handler.py", line 252, in _traverse
    result = _check_result(req, obj(req, form))
  File "/home/switowsk/.virtualenvs/master/lib/python2.7/site-packages/invenio/bibdocfile_webinterface.py", line 538, in managedocfilesasync
    uid=user_info['uid'])[1]
  File "/home/switowsk/.virtualenvs/master/lib/python2.7/site-packages/invenio/bibdocfile_managedocfiles.py", line 529, in create_file_upload_interface
    display_hidden_files)
  File "/home/switowsk/.virtualenvs/master/lib/python2.7/site-packages/invenio/bibdocfile_managedocfiles.py", line 1224, in build_updated_files_list
    abstract_bibdocs[bibdoc_name]['get_docname'] = rename or bibdoc_name
KeyError: 'png33'

-* Stack frame details

Frame build_updated_files_list in /home/switowsk/.virtualenvs/master/lib/python2.7/site-packages/invenio/bibdocfile_managedocfiles.py at line 1224
-------------------------------------------------------------------------------
      1221         elif action == "revise" and not file_path:
      1222             # revision of attributes of a file (description, name,
      1223             # comment or restriction) but no new file.
----> 1224             abstract_bibdocs[bibdoc_name]['get_docname'] = rename or bibdoc_name
      1225             abstract_bibdocs[bibdoc_name]['get_status'] = file_restriction
      1226             set_description_and_comment(abstract_bibdocs[bibdoc_name]['list_latest_files'],
      1227                                         description, comment)
-------------------------------------------------------------------------------
                 comment =  "''"
                  rename =  "'png333'"
    display_hidden_files =  'True'
                 bibdocs =  "[BibDoc(226, 'Main', False), BibDoc(223, 'Main', False), BibDoc(220, 'Main', False), BibDoc(221, 'Main', False), BibDoc(222, 'Main', False)]"
                 actions =  "[('revise', 'png3', *, 'png33', *, *, 'Main', 1, *), ('revise', 'png33', *, 'png333', *, *, 'Main', 1, *)]"
                     brd =  'BibRecDocs(1604802)'
        abstract_bibdocs =  '{\'png3\': {\'updated\': True, \'get_status\': \'\', \'get_docname\': \'png33\', \'list_latest_files\': [BibDocFile(\'/home/switowsk/.virtualenvs/master/var/data/files/g0/226/content.png;1\',  1, \'png3\', \'.png\', 1604802, 226, \'\', \'26dcf40401654750d4dd3c25060a6d55\', BibDocMoreInfo(226, "ccopy_reg\\n_reconstructor\\np1\\n(cinvenio.bibdocfile\\nBibDocMoreInfo\\np2\\nc__builtin__\\nobject\\np3\\nNtRp4\\n(dp5\\nS\'cache_reads\'\\np6\\nI01\\nsS\'docid\'\\np7\\nI226\\nsS\'format\'\\np8\\nNsS\' [...]
                 dirname =  "''"
    keep_previous_versions =  '1'
                filename =  "''"
        file_restriction =  "''"
                  bibdoc =  "BibDoc(222, 'Main', False)"
             bibdoc_name =  "'png33'"
               file_path =  "''"
                  status =  "''"
             description =  "''"
              bibdocfile =  'BibDocFile(\'/home/switowsk/.virtualenvs/master/var/data/files/g0/222/content.JPG;icon-640;1\',  1, \'DSC00795_1\', \'.JPG;icon-640\', 1604802, 222, \'\', \'3f3924f6f9f359b0c17c293f85384499\', BibDocMoreInfo(222, "ccopy_reg\\n_reconstructor\\np1\\n(cinvenio.bibdocfile\\nBibDocMoreInfo\\np2\\nc__builtin__\\nobject\\np3\\nNtRp4\\n(dp5\\nS\'cache_reads\'\\np6\\nI01\\nsS\'docid\'\\np7\\nI222\\nsS\'format\'\\np8\\nNsS\'cache\'\\np9\\n(dp10\\nS\'\'\\n(dp11\\nS\'flags\'\\np12\\n(dp13\\nsS\'description [...]
                       i =  '7'
                 doctype =  "'Main'"
                   recid =  '1604802'
                  action =  "'revise'"
                hidden_p =  'False'
              fileformat =  "''"

Frame create_file_upload_interface in /home/switowsk/.virtualenvs/master/lib/python2.7/site-packages/invenio/bibdocfile_managedocfiles.py at line 529
-------------------------------------------------------------------------------
       526     abstract_bibdocs = build_updated_files_list(bibdocs,
       527                                                 performed_actions,
       528                                                 recid or -1,
---->  529                                                 display_hidden_files)
       530 
       531     # If any, process form submitted by user
       532     if form:
-------------------------------------------------------------------------------
     can_rename_doctypes =  "['*']"
    doctypes_to_default_filename =  '{}'
                     uid =  '1'
    can_restrict_doctypes =  "['*']"
                 bibdocs =  "[BibDoc(226, 'Main', False), BibDoc(223, 'Main', False), BibDoc(220, 'Main', False), BibDoc(221, 'Main', False), BibDoc(222, 'Main', False)]"
               sbm_indir =  "''"
              file_label =  "'Choose a file'"
       description_label =  "'Description'"
     can_revise_doctypes =  "['*']"
    print_outside_form_tag =  'True'
                 minsize =  "''"
       performed_actions =  "[('revise', 'png3', *, 'png33', *, *, 'Main', 1, *), ('revise', 'png33', *, 'png333', *, *, 'Main', 1, *)]"
    can_comment_doctypes =  "['*']"
    max_files_for_doctype =  '{}'
          print_envelope =  'False'
    display_hidden_files =  'True'
             sbm_doctype =  "''"
    can_add_format_to_doctypes =  "['*']"
       can_keep_doctypes =  "['*']"
              parameters =  "(*, *, [('Main', 'Main document'), ('LaTeX', 'LaTeX'), ('Source', 'Source'), ('Additional', 'Additional File'), ('Audio', 'Audio file'), ('Video', 'Video file'), ('Script', 'Script'), ('Data', 'Data'), ('Figure', 'Figure'), ('Schema', 'Schema'), ('Graph', 'Graph'), ('Image', 'Image'), ('Drawing', 'Drawing'), ('Slides', 'Slides')], ['Main', 'LaTeX', 'Source', 'Additional', 'Audio', 'Video', 'Script', 'Data', 'Figure', 'Schema', 'Graph', 'Image', 'Drawing', 'Slides'], ['*'], ['*'], ['*'], ['*'] [...]
                      ln =  "'en'"
              sbm_curdir =  'None'
                 maxsize =  "''"
         include_headers =  'False'
             working_dir =  "'/home/switowsk/.virtualenvs/master/var/tmp-shared/websubmit_upload_interface_config_1/20131108_132656'"
    can_describe_doctypes =  "['*']"
         form_url_params =  "'?access=20131108_132656'"
                    body =  "''"
              show_links =  'True'
                doctypes =  "['Main', 'LaTeX', 'Source', 'Additional', 'Audio', 'Video', 'Script', 'Data', 'Figure', 'Schema', 'Graph', 'Image', 'Drawing', 'Slides']"
                    form =  "{'rename': [Field('rename', 'png55')], 'comment': [Field('comment', *)], 'copyright_e1': [Field('copyright_e1', *)], 'description': [Field('description', *)], 'fileTarget': [Field('fileTarget', 'png33')], 'ln': [Field('ln', 'en')], 'copyright_d1': [Field('copyright_d1', 'CERN')], 'copyright_f1': [Field('copyright_f1', *)], 'copyright_g1': [Field('copyright_g1', '2013')], 'access': [Field('access', '20131108_132656')], 'myfile': [Field('myfile', *)], 'license_b1': [Field('license_b1', *),  [...]
     can_delete_doctypes =  "['*']"
       doctypes_and_desc =  "[('Main', 'Main document'), ('LaTeX', 'LaTeX'), ('Source', 'Source'), ('Additional', 'Additional File'), ('Audio', 'Audio file'), ('Video', 'Video file'), ('Script', 'Script'), ('Data', 'Data'), ('Figure', 'Figure'), ('Schema', 'Schema'), ('Graph', 'Graph'), ('Image', 'Image'), ('Drawing', 'Drawing'), ('Slides', 'Slides')]"
    protect_hidden_files =  'True'
            keep_default =  'True'
          filename_label =  "'Name'"
                       _ =  '<bound method GNUTranslations.gettext of <gettext.GNUTranslations instance at 0x2c055f0>>'
      can_name_new_files =  'True'
    create_related_formats =  'True'
    restrictions_and_desc =  "[('', 'Public'), ('restricted', 'Restricted')]"
              bibrecdocs =  'BibRecDocs(1604802)'
           comment_label =  "'Comment'"
                   recid =  '1604802'
       restriction_label =  "'Access'"
              sbm_access =  "'20131108_132656'"

Frame managedocfilesasync in /home/switowsk/.virtualenvs/master/lib/python2.7/site-packages/invenio/bibdocfile_webinterface.py at line 538
-------------------------------------------------------------------------------
       535                                             sbm_indir=argd['indir'],
       536                                             sbm_access=argd['access'],
       537                                             sbm_doctype=argd['doctype'],
---->  538                                             uid=user_info['uid'])[1]
       539 
       540     __call__ = managedocfiles
-------------------------------------------------------------------------------
                    form =  "{'rename': [Field('rename', 'png55')], 'comment': [Field('comment', *)], 'copyright_e1': [Field('copyright_e1', *)], 'description': [Field('description', *)], 'fileTarget': [Field('fileTarget', 'png33')], 'ln': [Field('ln', 'en')], 'copyright_d1': [Field('copyright_d1', 'CERN')], 'copyright_f1': [Field('copyright_f1', *)], 'copyright_g1': [Field('copyright_g1', '2013')], 'access': [Field('access', '20131108_132656')], 'myfile': [Field('myfile', *)], 'license_b1': [Field('license_b1', *),  [...]
         include_headers =  'False'
                    self =  '<invenio.bibdocfile_webinterface.WebInterfaceManageDocFilesPages object at 0x581ca50>'
                     req =  '<invenio_devserver.wsgi.WSGIRequest object at 0x581c5d0>'
               user_info =  "{'uid': 1, 'agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:25.0) Gecko/20100101 Firefox/25.0', 'uri': '/record/managedocfilesasync?access=20131108_132656', 'precached_usegroups': True, 'session': '0a4e820723f5964e3b1fee61c07ab172', 'precached_useadmin': True, 'group': [], 'login_method': 'Local', 'precached_usepaperattribution': True, 'precached_usepaperclaim': True, 'precached_viewsubmissions': False, 'email': 'sebastian.witowski@cern.ch', 'precached_usealerts': True, 'precached_usestats' [...]
                   recid =  '1604802'
               auth_code =  '0'
                    argd =  "{'ln': 'en', 'access': '20131108_132656', 'recid': 1604802, 'doctype': *, 'indir': *}"

Frame _traverse in /home/switowsk/.virtualenvs/master/lib/python2.7/site-packages/invenio/webinterface_handler.py at line 252
-------------------------------------------------------------------------------
       249                 req.uri not in CFG_NO_LANG_RECOGNITION_URIS:
       250             ln = get_preferred_user_language(req)
       251             form.add_field('ln', ln)
---->  252         result = _check_result(req, obj(req, form))
       253         return result
       254 
       255     def __call__(self, req, form):
-------------------------------------------------------------------------------
                     obj =  '<bound method WebInterfaceManageDocFilesPages.managedocfilesasync of <invenio.bibdocfile_webinterface.WebInterfaceManageDocFilesPages object at 0x581ca50>>'
                    name =  "'managedocfilesasync'"
                    form =  "{'rename': [Field('rename', 'png55')], 'comment': [Field('comment', *)], 'copyright_e1': [Field('copyright_e1', *)], 'description': [Field('description', *)], 'fileTarget': [Field('fileTarget', 'png33')], 'ln': [Field('ln', 'en')], 'copyright_d1': [Field('copyright_d1', 'CERN')], 'copyright_f1': [Field('copyright_f1', *)], 'copyright_g1': [Field('copyright_g1', '2013')], 'access': [Field('access', '20131108_132656')], 'myfile': [Field('myfile', *)], 'license_b1': [Field('license_b1', *),  [...]
                 guest_p =  '0'
                     req =  '<invenio_devserver.wsgi.WSGIRequest object at 0x581c5d0>'
               component =  "'managedocfilesasync'"
                 do_head =  'False'
                    path =  '[]'
                    self =  '<invenio.bibdocfile_webinterface.WebInterfaceManageDocFilesPages object at 0x581ca50>'

Frame _traverse in /home/switowsk/.virtualenvs/master/lib/python2.7/site-packages/invenio/webinterface_handler.py at line 239
-------------------------------------------------------------------------------
       236         # renderer. We even pass it the parsed form arguments.
       237         if path:
       238             if hasattr(obj, '_traverse'):
---->  239                 return obj._traverse(req, path, do_head, guest_p)
       240             else:
       241                 raise apache.SERVER_RETURN, apache.HTTP_NOT_FOUND
       242 
-------------------------------------------------------------------------------
                     obj =  '<invenio.bibdocfile_webinterface.WebInterfaceManageDocFilesPages object at 0x581ca50>'
                    name =  'None'
                 guest_p =  '0'
                     req =  '<invenio_devserver.wsgi.WSGIRequest object at 0x581c5d0>'
               component =  "'record'"
                 do_head =  'False'
                    path =  "['managedocfilesasync']"
                    self =  '<invenio.webinterface_layout.WebInterfaceInvenio object at 0x4f6bd90>'

Frame _handler in /home/switowsk/.virtualenvs/master/lib/python2.7/site-packages/invenio/webinterface_handler.py at line 445
-------------------------------------------------------------------------------
       442                     args = cgi.parse_qs(req.args)
       443                     if 'debug' in args:
       444                         remote_debugger.error_msg(args['debug'])
---->  445             register_exception(req=req, alert_admin=True)
       446             raise
       447 
       448         # Serve an error by default.
-------------------------------------------------------------------------------
                     req =  '<invenio_devserver.wsgi.WSGIRequest object at 0x581c5d0>'
         allowed_methods =  "('GET', 'POST', 'HEAD', 'OPTIONS', 'PUT')"
                       g =  'None'
                 guest_p =  '0'
                    args =  "{'access': ['20131108_132656']}"
                     uri =  "'/record/managedocfilesasync'"
                    path =  "['record', 'managedocfilesasync']"
                    root =  '<invenio.webinterface_layout.WebInterfaceInvenio object at 0x4f6bd90>'
                bad_msie =  'None'
```

**Comment by tiborsimko** [comment]
@switowski Was there some progress with this issue in the CDS OPS code base?

**Comment by switowski** [comment]
@tiborsimko no, the problem is still there. I couldn't think of any easy solution for this.
It's a very uncommon for users to change the filename TWICE, so I don't think it's something very important to fix (we might keep in mind this problem for master and make sure we don't make the same mistake when designing new "Document File Manager")
