### ISSUE TITLE
OverflowError: It's impossible to iterate over an infinite set (from bibindex_engine/bibauthority_engine)

### ISSUE THREAD

**Issue by sbujam** [inveniosoftware/invenio#1650]
Originally on 2013-11-28

It seems that if records with authority_controlled fields that have an EMPTY 0 subfield, an exception is thrown from the indexing module (that tries to find authorities in these subfields and fails).

For example, `700__$0$aTestUser` will create the error.

The problem begins in bibindex_engine.py (around line 981) and can probably be avoided if get_index_strings_by_control_no (in bibauthority_engine) checks for empty control_no. The same may be needed in other bibauthority_engine functions.

FYI, the full exception is shown below:

```
* 2013-11-28 17:38:29 -> OverflowError: It's impossible to iterate over an infinite set. (intbitset.pyx:560:lib.intbitset.intbitset.__iter__ (intbitset.c:6047))

-* User details
No client information available

-* Traceback details 

Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/invenio/bibindex_engine.py", line 1435, in task_run_core
    wordTable.add_recIDs_by_date(task_get_option("modified"), task_get_option("flush"))
  File "/usr/lib64/python2.6/site-packages/invenio/bibindex_engine.py", line 821, in add_recIDs_by_date
    self.add_recIDs(alist, opt_flush)
  File "/usr/lib64/python2.6/site-packages/invenio/bibindex_engine.py", line 757, in add_recIDs
    just_processed = self.add_recID_range(i_low, i_high)
  File "/usr/lib64/python2.6/site-packages/invenio/bibindex_engine.py", line 902, in add_recID_range
    phrases = self.get_phrases_for_tokenizing(tag, recID1, recID2)
  File "/usr/lib64/python2.6/site-packages/invenio/bibindex_engine.py", line 986, in get_phrases_for_tokenizing
    new_strings = get_index_strings_by_control_no(control_no)
  File "/usr/lib64/python2.6/site-packages/invenio/bibauthority_engine.py", line 281, in get_index_strings_by_control_no
    rec_IDs = get_low_level_recIDs_from_control_no(control_no)
  File "/usr/lib64/python2.6/site-packages/invenio/bibauthority_engine.py", line 133, in get_low_level_recIDs_from_control_no
    recIDs = list(_get_low_level_recIDs_intbitset_from_control_no(control_no))
  File "intbitset.pyx", line 560, in lib.intbitset.intbitset.__iter__ (intbitset.c:6047)
OverflowError: It's impossible to iterate over an infinite set.
```

(BTW, I know that empty subfields should not appear, but I'm still using the old websubmit process and its quite difficult to always check for empty elements in .tpl files. Luckily bibedit will strip empty subfields before sending the record to the indexer)

**Comment by tiborsimko** [comment]
Moving to **v1.3.1** milestone as this is a bug fix, not a new feature.
