### ISSUE TITLE
BibAuthorID: test_save_matrix failure on Debian Squeeze 32-bit

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1678]
Originally on 2014-01-15

On Debian Squeeze 32-bit, using libhdf5-serial-dev 1.8.4-patch1-2, python 2.6.6-3+squeeze7, gcc 4:4.4.5-1, the following test fails:

```
Traceback (most recent call last):
  File "/usr/lib/python2.6/unittest.py", line 279, in run
    testMethod()
  File "/opt/invenio/lib/python/invenio/bibauthorid_bib_matrix_unit_tests.py", line 104, in test_save_matrix
    self.assertTrue(bmcs0[i,j] == loaded[i,j])
  File "/opt/invenio/lib/python/invenio/bibauthorid_bib_matrix.py", line 63, in __getitem__
    ret = self._matrix[entry]
  File "/usr/local/lib/python2.6/dist-packages/h5py/_hl/dataset.py", line 301, in __getitem__
    if self.shape == ():
  File "/usr/local/lib/python2.6/dist-packages/h5py/_hl/dataset.py", line 114, in _g_shape
    return self.id.shape
  File "h5d.pyx", line 123, in h5py.h5d.DatasetID.shape.__get__ (h5py/h5d.c:2003)
  File "h5d.pyx", line 282, in h5py.h5d.DatasetID.get_space (h5py/h5d.c:3229)
ValueError: not a dataset (Invalid arguments to routine: Inappropriate type)
```

**Comment by tiborsimko** [comment]
Debian Squeeze LTS [ended in February 2016](https://www.debian.org/releases/squeeze/). Closing.
