### ISSUE TITLE
WebSession: Nydus/Redis related tracebacks on Debian Squeeze

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1694]
Originally on 2014-01-27

On our Debian Squeeze build box, accessing some web pages leads to traceback related to sessions in Redis.

Here is info about versions:

```
$ dpkg -l python | grep ^ii
ii  python                             2.6.6-3+squeeze7   

$ dpkg -l redis-server | grep ^ii
ii  redis-server                       2:1.2.6-1  

$ pip freeze | grep -E '(nydus|redis)'
nydus==0.10.6
redis==2.9.0
```

Here is example traceback:

```
* 2014-01-27 15:44:07 -> ResponseError: unknown command 'SETEX' (connection.py:339:read_response)

-* User details
                                     agent: Python-urllib/2.6
                                     email: juliet.capulet@cds.cern.ch
                                     group: ['montague-family']
                                     guest: 0
                              login_method: Local
                                  nickname: juliet
            precached_canseehiddenmarctags: True
precached_permitted_restricted_collections: []
                    precached_sendcomments: True
                        precached_useadmin: True
                       precached_usealerts: True
                      precached_useapprove: False
                      precached_usebaskets: True
                       precached_usegroups: True
                        precached_useloans: True
                     precached_usemessages: True
             precached_usepaperattribution: True
                   precached_usepaperclaim: True
                        precached_usestats: False
                   precached_viewclaimlink: False
                 precached_viewsubmissions: False
                                   referer: <http://inveniobuilder0.cern.ch/youraccount/login>
                               remote_host: 
                                 remote_ip: 127.0.1.1
                                   session: de54daa433ab0f22961ed5ecc8486b1f
                                       uid: 6
                                       uri: </youraccount/login?>

-* Traceback details 

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/invenio/webinterface_handler_wsgi.py", line 552, in application
    session.save()
  File "/usr/local/lib/python2.6/dist-packages/invenio/session.py", line 306, in save
    uid)
  File "/usr/local/lib/python2.6/dist-packages/invenio/session.py", line 625, in save_in_storage
    timeout)
  File "/usr/local/lib/python2.6/dist-packages/nydus/db/base.py", line 133, in __call__
    return self.__cluster.execute(self.__path, args, kwargs)
  File "/usr/local/lib/python2.6/dist-packages/nydus/db/base.py", line 79, in execute
    results.append(func(*args, **kwargs))
  File "/usr/local/lib/python2.6/dist-packages/redis/client.py", line 1700, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/usr/local/lib/python2.6/dist-packages/redis/client.py", line 461, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.6/dist-packages/redis/client.py", line 471, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.6/dist-packages/redis/connection.py", line 339, in read_response
    raise response
ResponseError: unknown command 'SETEX'
```

In Debian Squeze backports, there is redis 2.4.15, so in the worst of cases we could recommend to upgrade.  In this case we should introduce a test for minimal Redis/Nydus version in "configure-tests.py", or even switch CFG_WEBSESSION_STORAGE back to   MySQL.

**Comment by jirikuncar** [comment]
Please note the python and server (major.minor) version should be the same `redis-server>=2.8` and `redis>=2.8`.

**Comment by tiborsimko** [comment]
Note that this ticket was calling for making an explicit version check in `configure-tests.py`, so that people don't get the same problem as observed on the build box.  (Redis version is already well specified in `requirements.txt`.)
