### ISSUE TITLE
WebComment: day is out of range for month

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1695]
Originally on 2014-01-31

When run at the end of the month, the following trackback happens in invenio.webcomment_tests.TestCalculateStartDate.test_with_random_values on_maint-1.0_ branch:

```
invenio.webcomment_tests.TestCalculateStartDate.test_with_random_values (from nosetests)

Failing for the past 1 build (Since #355 )
Took 0 ms.
Error Message

day is out of range for month
Stacktrace

Traceback (most recent call last):
  File "/usr/lib/python2.6/unittest.py", line 279, in run
    testMethod()
  File "/opt/invenio/lib/python/invenio/webcomment_tests.py", line 43, in test_with_random_values
    self.assert_(calculate_start_date('6m') > '2009-01-09 14:51:10')
  File "/opt/invenio/lib/python/invenio/webcomment.py", line 1243, in calculate_start_date
    yesterday = today.replace(year=final_nb_year, month=nb_month)
ValueError: day is out of range for month
```

**Comment by tiborsimko** [comment]
This was fixed in later releases (v1.1) by means of using `dateutil.relativedelta`.
