### ISSUE TITLE
BibDocFile: support CDATA when extracting text

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio#1696]
Originally on 2014-01-31

Currently, when an `.xml` file is converted to text in order to textify it, if it contains a CDATA section, this is not correctly handled:

```
[...]
Error in extracting text from bibdoc 971, version 1

- 2014-01-30 07:54:05 -> InvenioWebSubmitFileConverterError: Unexpected error when converting from /opt/invenio/var/data/files/g0/971/content.xml;1 to .txt (<class 'HTMLParser.HTMLParseError'>): unknown declaration: 'CDATA[${\\mathcal N}=1$', at line 42, column 31 (websubmit_file_converter.py:506:convert_file)

-* User details
No client information available

-* Traceback details 

Traceback (most recent call last):
  File "/opt/invenio/lib/python/invenio/bibdocfile_plugins/bom_textdoc.py", line 107, in extract_text
    convert_file(filename, os.path.join(self.basedir, '.text;%i' % version), '.txt', perform_ocr=perform_ocr, ln=ln)
  File "/usr/lib64/python2.6/site-packages/invenio/websubmit_file_converter.py", line 506, in convert_file
    raise InvenioWebSubmitFileConverterError("Unexpected error when converting from %s to %s (%s): %s" % (input_file, output_ext, type(err), err))
InvenioWebSubmitFileConverterError: Unexpected error when converting from /opt/invenio/var/data/files/g0/971/content.xml;1 to .txt (<class 'HTMLParser.HTMLParseError'>): unknown declaration: 'CDATA[${\\mathcal N}=1$', at line 42, column 31
[...]
```

An example of file that causes the failure is attached.

**Comment by tiborsimko** [comment]
There is no PR yet, and Invenio 1.1 is the old stable release, and we recommend to use Invenio 1.2 instead. Hence I'm closing this issue. If anyone encounters this problem, please reopen.
