### ISSUE TITLE
WebStat: date math troubles

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1715]
Originally on 2014-02-25

The following traceback happens for "last three months" stats:

```
* 2014-02-18 05:05:56 -> ValueError: day is out of range for month (webstat_engine.py:2206:create_graph_trend_flot)

[...]

uri: </stats/collection_population?ln=de&collection=All&format=flot&timespan=last+three+months&s_date=02%2F18%2F2014+00%3A00&f_date=02%2F18%2F2014+05%3A05&action_gen=Generate>

[...]

Traceback (most recent call last):
 File "/usr/local/lib/python2.6/dist-packages/invenio/webinterface_handler_wsgi.py", line 514, in application
   ret = invenio_handler(req)
 File "/usr/local/lib/python2.6/dist-packages/invenio/webinterface_handler.py", line 371, in _profiler
   return _handler(req)
 File "/usr/local/lib/python2.6/dist-packages/invenio/webinterface_handler.py", line 433, in _handler
   return root._traverse(req, path, False, guest_p)
 File "/usr/local/lib/python2.6/dist-packages/invenio/webinterface_handler.py", line 240, in _traverse
   return obj._traverse(req, path, do_head, guest_p)
 File "/usr/local/lib/python2.6/dist-packages/invenio/webinterface_handler.py", line 253, in _traverse
   result = _check_result(req, obj(req, form))
 File "/usr/local/lib/python2.6/dist-packages/invenio/webstat_webinterface.py", line 200, in collection_population
   body=perform_display_keyevent('collection population', argd, req, ln=ln),
 File "/usr/local/lib/python2.6/dist-packages/invenio/webstat.py", line 1348, in perform_display_keyevent
   os.path.basename(filename), settings, ln=ln) + sql
 File "/usr/local/lib/python2.6/dist-packages/invenio/webstat.py", line 1654, in _perform_display_event
   create_graph_trend(data, path, settings)
 File "/usr/local/lib/python2.6/dist-packages/invenio/webstat_engine.py", line 1971, in create_graph_trend
   create_graph_trend_flot(trend, path, settings)
 File "/usr/local/lib/python2.6/dist-packages/invenio/webstat_engine.py", line 2206, in create_graph_trend_flot
   next = current.replace(day=31)
ValueError: day is out of range for month
```

**Comment by tiborsimko** [comment]
There is no PR for this issue, hence closing it as per the `legacy` code base freeze; it is addressed in `master` code base differently.
