### ISSUE TITLE
bibencode_tester.py failing tests

### ISSUE THREAD

**Issue by filiptuhy** [inveniosoftware/invenio#1725]
##### What I did:

invenio 1.1.2 nad invenio 1.1.3
`python -u www-data -- python lib/python/invenio/bibencode_tester.py`
##### What was expected :

all tests were expected to pass.
##### What happened:

```
test_setUp (__main__.SetupTester) ... Downloading sample video ...
Starting encoding ...
  An FFMPEG error has appeared, see log
FAIL
test_aspect_string_to_float (__main__.TestUtilsFunctions)
Tests if string contains an aspect ratio ... ok
test_is_seconds (__main__.TestUtilsFunctions)
Tests if given value is seconds like ... ok
test_is_timecode (__main__.TestUtilsFunctions)
Test if given value is a timecode ... ok
test_seconds_to_timecode (__main__.TestUtilsFunctions)
Convert seconds to timecode ... ok
test_timcode_to_seconds (__main__.TestUtilsFunctions)
Convert timecode to seconds ... ok
test_assure_quality (__main__.TestEncodeFunctions)
Test if the quality is detected correctly ... ERROR
test_determine_aspect (__main__.TestEncodeFunctions)
Tests if the aspect is correctly detected ... FAIL
test_determine_resolution (__main__.TestEncodeFunctions)
Tests if the resolution is correctly calculated ... ERROR
===================================================================
 ERROR: test_assure_quality (__main__.TestEncodeFunctions)
 Test if the quality is detected correctly
-------------------------------------------------------------------
 Traceback (most recent call last):
File "bibencode_tester.py", line 262, in test_assure_quality
  self.assertEqual(bibencode_encode.assure_quality(video01_out03,
None, 1920, 1080, 6000000, True, 1.0), True)
 File
"/usr/local/lib/python2.7/dist-packages/invenio/bibencode_encode.py", line
194, in assure_quality
     fwidth = aspect_ratio_tuple[1]
 TypeError: 'NoneType' object has no attribute '__getitem__'
===================================================================
 ERROR: test_determine_resolution (__main__.TestEncodeFunctions)
 Tests if the resolution is correctly calculated
-------------------------------------------------------------------
 Traceback (most recent call last):
   File "bibencode_tester.py", line 219, in test_determine_resolution
self.assertEqual(bibencode_encode.determine_resolution_preserving_aspect(video01_out03,
1920, 1080, None), "1920x1080")
  File
"/usr/local/lib/python2.7/dist-packages/invenio/bibencode_encode.py", line
120, in determine_resolution_preserving_aspect
     if aspect_ratio_tuple[0] is None:
 TypeError: 'NoneType' object has no attribute '__getitem__'
===================================================================
 FAIL: test_setUp (__main__.SetupTester)
-------------------------------------------------------------------
 Traceback (most recent call last):
   File "bibencode_tester.py", line 118, in test_setUp
     self.assertEqual(encode_video(video01, video01_out01, "libfaac",
"libx264", 128000, 8000000, "1920x1080", 1, "-vpre medium",
metadata=metadata, update_fnc=printr), 1)
 AssertionError: 0 != 1
===================================================================
 FAIL: test_determine_aspect (__main__.TestEncodeFunctions)
 Tests if the aspect is correctly detected
-------------------------------------------------------------------
 Traceback (most recent call last):
   File "bibencode_tester.py", line 212, in test_determine_aspect

self.assertEqual(bibencode_encode.determine_aspect(video01_out02), ("16:9",
1920, 1080))
AssertionError: None != ('16:9', 1920, 1080)
------------------------------------------------------------------
Ran 9 tests in 50.831s 
```

I consulted this with Yoan Blanc, he added some tests, see here http://pastie.org/private/xcsmcbef9gv0f16fzhypoq and still got fails, so it seems it is failing for MOV video format anamorphic, but also the unit tests that are there right now .

**Comment by tiborsimko** [comment]
@ludmilamarian @drjova Do you have any improvements regarding legacy BibEncode?

**Comment by drjova** [comment]
@tiborsimko (@ludmilamarian please correct me if I'm wrong) I think there are no improvements for BibEncode so far.

**Comment by ludmilamarian** [comment]
Indeed, the ones that we had have been merged already.
