### ISSUE TITLE
BibAuthorID: broken disambiguation on Atlantis demo site

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#1862]
BibAuthorID stopped working for Atlantis demo site.

Firstly, collection treatment should be amended:

```
$ diff -u modules/bibauthorid/lib/bibauthorid_config.py /opt/invenio/lib/python/invenio/
--- modules/bibauthorid/lib/bibauthorid_config.py       2014-06-20 14:43:36.823044058 +0200
+++ /opt/invenio/lib/python/invenio/bibauthorid_config.py       2014-06-23 16:06:45.973087504 +0200
@@ -92,8 +92,10 @@
 # Special for ADS: Focus on ASTRONOMY collection
 if GLOBAL_CONFIG and CFG_ADS_SITE:
     LIMIT_TO_COLLECTIONS = ["ASTRONOMY"]
-else:
+elif CFG_INSPIRE_SITE:
     LIMIT_TO_COLLECTIONS = ['HEP']
+else:
+    LIMIT_TO_COLLECTIONS = []

 # Exclude documents that are visible in a collection mentioned here:
 EXCLUDE_COLLECTIONS = ["HEPDATA","Data", "HEPNAMES", "INST", "Deleted", "DELETED", "deleted"]
```

Secondly, location of Tortoise cache should be put under `/opt/invenio/var/cache/bibauthorid/tortoise_cache` by default.  Currently one has to do:

```
$ sudo mkdir /opt/tortoise_cache/
$ sudo chown www-data.www-data /opt/tortoise_cache/
```

Thirdly, the first process runs fine:

```
$ sudo -u www-data /opt/invenio/bin/bibauthorid -u admin --update-personid --all-records -v 9
```

and populates well tables:

```
mysql> SELECT * FROM aidPERSONIDPAPERS LIMIT 5;
+----------+--------------+--------------+--------+-------------------+------+------+---------------------+
| personid | bibref_table | bibref_value | bibrec | name              | flag | lcul | last_updated        |
+----------+--------------+--------------+--------+-------------------+------+------+---------------------+
|        8 | 100          |            1 |      1 | Photolab          |    0 |    0 | 2014-06-23 16:06:53 |
|        9 | 100          |            2 |      2 | Loïez, Patrice    |    0 |    0 | 2014-06-23 16:06:53 |
|       10 | 100          |            3 |      4 | Caron, J. L.      |    0 |    0 | 2014-06-23 16:06:54 |
|       11 | 700          |            2 |      8 | Hobson, M. P.     |    0 |    0 | 2014-06-23 16:06:54 |
|       12 | 100          |            4 |      8 | Efstathiou, G. P. |    0 |    0 | 2014-06-23 16:06:54 |
+----------+--------------+--------------+--------+-------------------+------+------+---------------------+
5 rows in set (0.01 sec)
```

but the second process does not run well:

```
$ sudo -u www-data /opt/invenio/bin/bibauthorid --disambiguate --from-scratch -u admin
```

for it prints many warnings of the kind:

```
Bib_matrix: error occurred while loading bibmap, cleaning...  <type
exceptions.IOError'> [Errno 2] No such file or directory:
u'/opt/tortoise_cache/mc/mcmahon-bibmap.pickle'
Bib_matrix: error occurred while loading bibmap, cleaning...  <type
exceptions.IOError'> [Errno 2] No such file or directory:
u'/opt/tortoise_cache/mc/mcmahon-bibmap.pickle'
Bib_matrix: error occurred while loading bibmap, cleaning...  <type
exceptions.IOError'> [Errno 2] No such file or directory:
```

and ends with a traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/invenio/bibtask.py", line 606, in task_init
    ret = _task_run(task_run_fnc)
  File "/usr/local/lib/python2.7/dist-packages/invenio/bibtask.py", line 1146, in _task_run
    if callable(task_run_fnc) and task_run_fnc():
  File "/usr/local/lib/python2.7/dist-packages/invenio/bibauthorid_daemon.py", line 157, in _task_run_core
    run_tortoise(bool(bibtask.task_get_option("from_scratch")))
  File "/usr/local/lib/python2.7/dist-packages/invenio/bibauthorid_daemon.py", line 307, in run_tortoise
    tortoise_from_scratch()
  File "/usr/local/lib/python2.7/dist-packages/invenio/bibauthorid_tortoise.py", line 95, in tortoise_from_scratch
    schedule_workers(lambda x: force_create_matrix(x, force=True), cluster_sets)
  File "/usr/local/lib/python2.7/dist-packages/invenio/bibauthorid_general_utils.py", line 328, in schedule_workers
    new_proc = mp.Process(target=function, args=(jobs.pop(),))
IndexError: pop from empty list
```

**Comment by sbujam** [comment]
In addition to what Tibor mentions, bibauthorid_daemon.py seems to throw the following exception when bibauthorid -u admin --disambiguate **--from-scratch**  is called:
```
Unexpected error occurred: local variable 'tortoise_db_name' referenced before assignment.
```
This could be easily solved by *something like this*:
```
--- /downloads/invenio/modules/bibauthorid/lib/bibauthorid_daemon.py.orig       2015-02-06 15:49:54.651000000 +0200
+++ /downloads/invenio/modules/bibauthorid/lib/bibauthorid_daemon.py    2015-02-06 15:50:44.670000000 +0200
@@ -303,12 +303,11 @@
 def run_tortoise(from_scratch):
     from invenio.bibauthorid_tortoise import tortoise, tortoise_from_scratch

+    start_time = get_db_time()
+    tortoise_db_name = 'tortoise'
     if from_scratch:
         tortoise_from_scratch()
     else:
-        start_time = get_db_time()
-        tortoise_db_name = 'tortoise'
-
         last_run = get_user_logs(userinfo=tortoise_db_name, only_most_recent=True)
         if last_run:
             modified = get_modified_papers_since(last_run[0][2])
```

Maybe (or I should say probably) this was fixed in a separate commit along with other enhancements/fixes, but since it's not yet merged to master, I thought I should also mention it here in case it helps anyone.
