### ISSUE TITLE
travis: apparent failure of tests in a passed build

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#2210]
Taking last "pu" branch tip 0685158ab929851209c3d925f1354e6663064296, the corresponding Travis build is here: 

- https://s3.amazonaws.com/archive.travis-ci.org/jobs/33838310/log.txt

The build apparently passes:

```
[...]

Ran 951 tests in 517.090s

OK (skipped=10)
travis_time:end:10e87675:start=1409259747305413522,finish=1409260285198867748,duration=537893454226
[0K
[32;1mThe command "python setup.py test" exited with 0.[0m

Done. Your build exited with 0.
```

But the test report show many apparent failures:

```
ImportError: No module named bibrecord

[...]

  File "/home/travis/build/inveniosoftware/invenio/invenio/modules/oauthclient/handlers.py", line 340, in inner
    return f(args[0], remote, *args[1:], **kwargs)
TypeError: handler_invalid() takes exactly 1 argument (3 given)

[...]

Traceback (most recent call last):
  File "/home/travis/build/inveniosoftware/invenio/invenio/ext/legacy/layout.py", line 299, in <module>
    from invenio.legacy.authorlist.webinterface import WebInterfaceAuthorlistPages
ImportError: No module named authorlist.webinterface

[...]

  File "/home/travis/build/inveniosoftware/invenio/invenio/modules/workflows/tasks/sample_tasks.py", line 50, in call_c
    raise ZeroDivisionError
ZeroDivisionError
, id_workflow: dc49d764-2ef7-11e4-8a29-71974776cdb9, id_object: 0, payload: '[]')

ok
```

and many others.

Firstly, shouldn't the build fail when some of the above situations happen? Secondly, shall we decorate those tests that are known to fail with `@nottest` and `FIXME` and have dedicated planned issues for them?  Thirdly, shall we silence the verbosity of those tests that test for failure in order to have a "clean" output?

**Comment by jirikuncar** [comment]
Many problems has been fixed in #2223 and #2842.
