### ISSUE TITLE
docs: clean Sphinx autodoc build dependencies

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio#2249]
As a follow-up on https://github.com/inveniosoftware/invenio/issues/2244#issuecomment-54947587, we may want to clean autodoc building of documentation via `inveniomanage documentation build`.  E.g. `github3` is needed for `oauthclient`, but this is not declared in `docs` in `setup.py`.  Hence the current output: *(even though docs are built mostly fine)*

```console
$ inveniomanage documentation build
Running Sphinx v1.2.3
Template {0} not found, pip install it
loading pickled environment... not yet created
loading intersphinx inventory from http://flask.pocoo.org/docs/objects.inv...
loading intersphinx inventory from http://docs.sqlalchemy.org/en/latest/objects.inv...
loading intersphinx inventory from http://jinja.pocoo.org/docs/objects.inv...
loading intersphinx inventory from http://werkzeug.pocoo.org/docs/objects.inv...
loading intersphinx inventory from http://webassets.readthedocs.org/en/latest/objects.inv...
loading intersphinx inventory from https://docs.python.org/2.7/objects.inv...
loading intersphinx inventory from http://flask-assets.readthedocs.org/en/latest/objects.inv...
loading intersphinx inventory from http://flask-script.readthedocs.org/en/latest/objects.inv...l
oading intersphinx inventory from http://flask-registry.readthedocs.org/en/latest/objects.inv...
building [websupport]: targets for 79 source files that are out of date
updating environment: 79 added, 0 changed, 0 removed
reading sources... [100%] utils/washers                                                                                                                      
/home/vagrant/.virtualenvs/invenio2/src/invenio/docs/ext/elasticsearch.rst:21: WARNING: autodoc: failed to import module u'invenio.ext.elasticsearch'; the fo
llowing exception was raised:                                                                                                                               
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/ext/elasticsearch/__init__.py", line 86, in <module>
    from pyelasticsearch import ElasticSearch as PyElasticSearch
ImportError: No module named pyelasticsearch
/home/vagrant/.virtualenvs/invenio2/src/invenio/docs/modules/jsonalchemy.rst:540: WARNING: autodoc: failed to import class u'MongoDBStorage' from module u'in
venio.modules.jsonalchemy.jsonext.engines.mongodb_pymongo'; the following exception was raised:                                                             
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/jsonalchemy/jsonext/engines/mongodb_pymongo.py", line 22, in <module>
    import pymongo
ImportError: No module named pymongo
/home/vagrant/.virtualenvs/invenio2/src/invenio/docs/modules/oauthclient.rst:37: WARNING: autodoc: failed to import module u'invenio.modules.oauthclient.cont
rib.github'; the following exception was raised:                                                                                                            
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/oauthclient/contrib/github.py", line 80, in <module>
    import github3
ImportError: No module named github3
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] utils/washers                                                                                                                       
writing additional files... genindex py-modindex search
copying images... [100%] _static/admin/bibformat-guide-bft_manage.png                                                                                        
copying static files... done
copying extra files... done
dumping object inventory... done
build succeeded, 3 warnings.
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/bin/inveniomanage", line 9, in <module>
    load_entry_point('Invenio==1.9999.3.dev20140903181947', 'console_scripts', 'inveniomanage')()
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/base/manage.py", line 103, in main
    manager.run()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/ext/script/__init__.py", line 141, in __call__
    res = super(SignalingCommand, self).__call__(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask/ctx.py", line 386, in __exit__
    self.auto_pop(exc_value)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask/ctx.py", line 374, in auto_pop
    self.pop(exc)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask/ctx.py", line 357, in pop
    % (rv, self)
AssertionError: Popped wrong request context.  (<RequestContext 'http://localhost/' [GET] of invenio.base> instead of <RequestContext 'http://localhost/' [GE
T] of invenio.base>)                                                                                 
```

**Comment by jirikuncar** [comment]
Sphinx build is part of CI in each repository.
