### ISSUE TITLE
mixer: sources/ folder not created automatically

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#2446]
When running:

```
$ inveniomanage database dump
```

In order to produce the mixer .json files, the command fails:

```
>>> Mixer: Unblending DB
Traceback (most recent call last):
  File "/home/jmartinm/.virtualenvs/pu-inspire/bin/inveniomanage", line 9, in <module>
    load_entry_point('Invenio==1.9999.4.dev20141021150513', 'console_scripts', 'inveniomanage')()
  File "/home/jmartinm/.virtualenvs/pu-inspire/src/invenio/invenio/base/manage.py", line 103, in main
    manager.run()
  File "/home/jmartinm/.virtualenvs/pu-inspire/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/jmartinm/.virtualenvs/pu-inspire/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/jmartinm/.virtualenvs/pu-inspire/src/invenio/invenio/ext/script/__init__.py", line 143, in __call__
    post_command.send(sender, args=args, **kwargs)
  File "/home/jmartinm/.virtualenvs/pu-inspire/local/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/jmartinm/.virtualenvs/pu-inspire/src/invenio/invenio/ext/mixer/__init__.py", line 205, in unblend_all
    mixer.unblend(mixers[table.name])
  File "/home/jmartinm/.virtualenvs/pu-inspire/src/invenio/invenio/ext/mixer/__init__.py", line 179, in unblend
    with scheme.__blender__.Dump(scheme) as dump:
  File "/home/jmartinm/.virtualenvs/pu-inspire/src/invenio/invenio/ext/mixer/__init__.py", line 60, in __init__
    os.makedirs(os.path.dirname(directory))
  File "/home/jmartinm/.virtualenvs/pu-inspire/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/jmartinm/.virtualenvs/pu-inspire/src/inspire/inspire/base/mixer'
```

I would expect the ``sources/`` folder to be created automatically

**Comment by jirikuncar** [comment]
Fixed in 1f43d449.
