### ISSUE TITLE
BibConvert: fails on CentOS, with Python 2.7.5

### ISSUE THREAD

**Issue by frecar** [inveniosoftware/invenio#2563]
Related issue: http://stackoverflow.com/questions/13019495/import-error-when-using-xpath-from-pyxml-0-8-4

```
[root@invenio2 1416848800_6383]# /opt/invenio/bin/bibconvert -l1 -d'/data/submit/running/tesis/1416848800_6383' -Cs'/opt/invenio/etc/bibconvert/config/tesis.tpl' -Ct'/opt/invenio/etc/bibconvert/config/tesiscreate.tpl' > /data/submit/running/tesis/1416848800_6383/dummy_marcxml_rec
Traceback (most recent call last):
  File "/opt/invenio/bin/bibconvert", line 49, in <module>
    from invenio import bibconvert_bfx_engine
  File "/usr/lib64/python2.7/site-packages/invenio/bibconvert_bfx_engine.py", line 43, in <module>
    from xml.xpath import Evaluate
  File "/usr/lib64/python2.7/site-packages/_xmlplus/xpath/__init__.py", line 112, in <module>
    from pyxpath import ExprParserFactory
  File "/usr/lib64/python2.7/site-packages/_xmlplus/xpath/pyxpath.py", line 60, in <module>
    from xml.xpath.ParsedAbbreviatedAbsoluteLocationPath import ParsedAbbreviatedAbsoluteLocationPath
  File "/usr/lib64/python2.7/site-packages/_xmlplus/xpath/ParsedAbbreviatedAbsoluteLocationPath.py", line 27
    as = ParsedAxisSpecifier.ParsedAxisSpecifier('descendant-or-self')
     ^

**Comment by tiborsimko** [comment]
This problem lies outside of Invenio.  Which Invenio version was this obtained with?  Have you used recommended libraries from requirements.txt?  Note that for the (unreleased) master version, it is enough to use lxml, so this problem should not appear.  

Also note that the error occurs with the bfx engine that has been unused since years and is now deprecated (#2124).   I'll remove it from v1.2 altogether.
