### ISSUE TITLE
Issues with flashed messages

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#2625]
This issue is twofold:

1. There is no easy way of customizing the flashed messages coming from the Flask-Login integration. Should we have a configuration variable or something to override it? For example, in INSPIRE we want to override it (e.g. remove it) due to redundant information. ("Please sign in etc.." displayed several times on the page)

2. If you remove the call to flashed_messages() in the page.html template, you can get errors such as the one below when accessing certain pages (for example, Holding Pen table):

```
Traceback (most recent call last):
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jlavik/envs/labs/src/invenio/invenio/ext/legacy/__init__.py", line 128, in __call__
    response = self.app.handle_exception(e)
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/flask_restful/__init__.py", line 258, in error_router
    return original_handler(e)
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jlavik/envs/labs/src/invenio/invenio/ext/legacy/__init__.py", line 124, in __call__
    response = self.app.full_dispatch_request()
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/flask_restful/__init__.py", line 258, in error_router
    return original_handler(e)
  File "/home/jlavik/envs/labs/src/invenio/invenio/base/wrappers.py", line 125, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "/home/jlavik/envs/labs/src/invenio/invenio/base/decorators.py", line 104, in decorated_function
    return jsonify(**ctx)
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/flask/json.py", line 238, in jsonify
    indent=indent),
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/simplejson/__init__.py", line 382, in dumps
    **kw).encode(obj)
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/simplejson/encoder.py", line 269, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/simplejson/encoder.py", line 348, in iterencode
    return _iterencode(o, 0)
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/flask/json.py", line 83, in default
    return _json.JSONEncoder.default(self, o)
  File "/home/jlavik/envs/labs/lib/python2.7/site-packages/simplejson/encoder.py", line 246, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: lu'You are logged in as admin.' is not JSON serializable
```

Note that you get this error when DataTables is querying `holdingpen.load_table` to get data.

Could it be that it is not taken off some flash stack?

See also https://github.com/mitsuhiko/flask-babel/issues/31

CC: @jmartinm

**Comment by jirikuncar** [comment]
@jalavik can you provide steps to reproduce this issue?

**Comment by jalavik** [comment]
@jirikuncar Actually, with Invenio Demosite I am unable to reproduce it right now. I will investigate more why this happens on the INSPIRE side. In the meanwhile I can close this issue and re-open it if I am able to find a real problem in Invenio.
