### ISSUE TITLE
BibUpload: dog piling fix barks back

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#2665]
The commit https://github.com/inveniosoftware/invenio/commit/16fcacc7fbeb4fbece1c44823f5f66437ca11483 to prevent dog-piling of `get_record` calls seem to cause an issue when running `bibupload -ir` jobs on our labs servers:

```
Traceback (most recent call last):
  File "/opt/Inspire-2.0.1.dev20141107094016/lib/python2.7/site-packages/invenio/legacy/bibsched/bibtask.py", line 615, in task_init
    ret = _task_run(task_run_fnc)
  File "/opt/Inspire-2.0.1.dev20141107094016/lib/python2.7/site-packages/invenio/legacy/bibsched/bibtask.py", line 1191, in _task_run
    if callable(task_run_fnc) and task_run_fnc():
  File "/opt/Inspire-2.0.1.dev20141107094016/lib/python2.7/site-packages/invenio/legacy/bibupload/engine.py", line 2993, in task_run_core
    results_for_callback=results_for_callback)
  File "/opt/Inspire-2.0.1.dev20141107094016/lib/python2.7/site-packages/invenio/legacy/bibupload/engine.py", line 2919, in bibupload_records
    tmp_vers = tmp_vers)
  File "/opt/Inspire-2.0.1.dev20141107094016/lib/python2.7/site-packages/invenio/legacy/bibupload/engine.py", line 299, in bibupload
    rec_old = get_record(rec_id)
UnboundLocalError: local variable 'get_record' referenced before assignment
```

Reverting the fix causes the error to go away. Question is, what causes this?

**Comment by jirikuncar** [comment]
Closed via #2667
