### ISSUE TITLE
accounts: error if you try to access to "Your account" and you are not logged in

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#2726]
I tried to open the register form and I see that we have this breadcrumbs: `Home > Your account > Register`.
If you try to click on "Your account", it returns `AttributeError: 'NoneType' object has no attribute 'settings'`.

```python
--------------------------------------------------------------------------------
ERROR in wrappers [/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/ext/logging/wrappers.py:310]:

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/ext/legacy/__init__.py", line 124, in __call__
    response = self.app.full_dispatch_request()
  File "/home/vagrant/.virtualenvs/invenio2/src/flask/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/base/wrappers.py", line 125, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/home/vagrant/.virtualenvs/invenio2/src/flask/flask/app.py", line 1423, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.virtualenvs/invenio2/src/flask/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask_login.py", line 755, in decorated_view
    return func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/accounts/views/accounts.py", line 211, in index
    map(lambda x: x(), _USER_SETTINGS.values()))
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/accounts/views/accounts.py", line 211, in <lambda>
    map(lambda x: x(), _USER_SETTINGS.values()))
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/dashboard/user_settings.py", line 35, in __init__
    super(DashboardSettings, self).__init__()
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/dashboard/settings.py", line 144, in __init__
    self.storage = self.storage_builder(self.keys)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/dashboard/settings.py", line 109, in <lambda>
    return lambda self, key: UserSettingsStorage(key, attr)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/dashboard/settings.py", line 81, in __init__
    self._data = dict(self._user.settings.get(self._attr, {}))
AttributeError: 'NoneType' object has no attribute 'settings'
10.0.2.2 - - [30/Jan/2015 09:37:57] "GET /youraccount/display HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/src/flask/flask/app.py", line 1883, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/ext/legacy/__init__.py", line 128, in __call__
    response = self.app.handle_exception(e)
  File "/home/vagrant/.virtualenvs/invenio2/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/home/vagrant/.virtualenvs/invenio2/src/flask/flask/app.py", line 1445, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/ext/legacy/__init__.py", line 124, in __call__
    response = self.app.full_dispatch_request()
  File "/home/vagrant/.virtualenvs/invenio2/src/flask/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.virtualenvs/invenio2/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/base/wrappers.py", line 125, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/home/vagrant/.virtualenvs/invenio2/src/flask/flask/app.py", line 1423, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.virtualenvs/invenio2/src/flask/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.virtualenvs/invenio2/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/home/vagrant/.virtualenvs/invenio2/lib/python2.7/site-packages/flask_login.py", line 755, in decorated_view
    return func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/accounts/views/accounts.py", line 211, in index
    map(lambda x: x(), _USER_SETTINGS.values()))
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/accounts/views/accounts.py", line 211, in <lambda>
    map(lambda x: x(), _USER_SETTINGS.values()))
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/dashboard/user_settings.py", line 35, in __init__
    super(DashboardSettings, self).__init__()
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/dashboard/settings.py", line 144, in __init__
    self.storage = self.storage_builder(self.keys)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/dashboard/settings.py", line 109, in <lambda>
    return lambda self, key: UserSettingsStorage(key, attr)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/dashboard/settings.py", line 81, in __init__
    self._data = dict(self._user.settings.get(self._attr, {}))
AttributeError: 'NoneType' object has no attribute 'settings'
```

**Comment by jirikuncar** [comment]
### Proposal

- [ ] HOTFIX allow `/youraccount` url for logged users only
- [ ] removal of `user_settings` and migrating them to match *Zenodo* style.

**Comment by hachreak** [comment]
False alarm.. XD
It's because with `TESTING = True` in configuration, it doesn't ask you to login. T_T
