### ISSUE TITLE
inveniomanage demosite populate errors

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#2750]
Hi at all,
I tried to run `inveniomanage demosite populate --yes-i-know` and  I received these errors.
Someone can help me? :)

```python
--------------------------------------------------------------------------------
ERROR in wrappers [/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/ext/logging/wrappers.py:310]:

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsched/bibtask.py", line 615, in task_init
    ret = _task_run(task_run_fnc)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsched/bibtask.py", line 1191, in _task_run
    if callable(task_run_fnc) and task_run_fnc():
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibindex/engine.py", line 2169, in task_run_core
    task_get_option("cmd") == "del"))
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibindex/engine.py", line 559, in find_affected_records_for_index
    AND (SELECT COUNT(*) FROM hstRECORD WHERE id_bibrec=id)=1""", (min_last_updated,))
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/dbquery_mysql.py", line 280, in run_sql
    rc = cur.execute(sql, param)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1052, "Column 'id' in field list is ambiguous")
2015-02-06 13:20:12 -->
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsched/bibtask.py", line 615, in task_init
    ret = _task_run(task_run_fnc)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsched/bibtask.py", line 1191, in _task_run
    if callable(task_run_fnc) and task_run_fnc():
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibindex/engine.py", line 2169, in task_run_core
    task_get_option("cmd") == "del"))
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibindex/engine.py", line 559, in find_affected_records_for_index
    AND (SELECT COUNT(*) FROM hstRECORD WHERE id_bibrec=id)=1""", (min_last_updated,))
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/dbquery_mysql.py", line 280, in run_sql
    rc = cur.execute(sql, param)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1052, "Column 'id' in field list is ambiguous")
2015-02-06 13:20:12 --> Unexpected error occurred: (1052, "Column 'id' in field list is ambiguous").
2015-02-06 13:20:12 --> Traceback is:
2015-02-06 13:20:12 -->   File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsched/bibtask.py", line 615, in task_init
2015-02-06 13:20:12 -->     ret = _task_run(task_run_fnc)
2015-02-06 13:20:12 -->   File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsched/bibtask.py", line 1191, in _task_run
2015-02-06 13:20:12 -->     if callable(task_run_fnc) and task_run_fnc():
2015-02-06 13:20:12 -->   File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibindex/engine.py", line 2169, in task_run_core
2015-02-06 13:20:12 -->     task_get_option("cmd") == "del"))
2015-02-06 13:20:12 -->   File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibindex/engine.py", line 559, in find_affected_records_for_index
2015-02-06 13:20:12 -->     AND (SELECT COUNT(*) FROM hstRECORD WHERE id_bibrec=id)=1""", (min_last_updated,))
2015-02-06 13:20:12 -->   File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/dbquery_mysql.py", line 280, in run_sql
2015-02-06 13:20:12 -->     rc = cur.execute(sql, param)
2015-02-06 13:20:12 -->   File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
2015-02-06 13:20:12 -->     self.errorhandler(self, exc, value)
2015-02-06 13:20:12 -->   File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
2015-02-06 13:20:12 -->     raise errorclass, errorvalue
2015-02-06 13:20:12 --> Exiting.
```

```python
--------------------------------------------------------------------------------
ERROR in wrappers [/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/ext/logging/wrappers.py:310]:

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsched/bibtask.py", line 615, in task_init
    ret = _task_run(task_run_fnc)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsched/bibtask.py", line 1191, in _task_run
    if callable(task_run_fnc) and task_run_fnc():
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/daemon.py", line 366, in task_run_core
    executed_correctly = rebalance(methods)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/daemon.py", line 173, in rebalance
    return run_bibsort_rebalance(method_list)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/engine.py", line 913, in run_bibsort_rebalance
    bibsort_methods[name]['washer'])
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/engine.py", line 279, in run_sorting_method
    sort_dict(field_data_dictionary, CFG_BIBSORT_WEIGHT_DISTANCE, run_sorting_for_rnk, sorting_locale)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/engine.py", line 407, in sort_dict
    sorted_records_list = sorted(dictionary, key=dictionary.__getitem__, cmp=locale.strcoll, reverse=False)
TypeError: coercing to Unicode: need string or buffer, list found
2015-02-06 13:20:56 -->
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsched/bibtask.py", line 615, in task_init
    ret = _task_run(task_run_fnc)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsched/bibtask.py", line 1191, in _task_run
    if callable(task_run_fnc) and task_run_fnc():
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/daemon.py", line 366, in task_run_core
    executed_correctly = rebalance(methods)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/daemon.py", line 173, in rebalance
    return run_bibsort_rebalance(method_list)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/engine.py", line 913, in run_bibsort_rebalance
    bibsort_methods[name]['washer'])
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/engine.py", line 279, in run_sorting_method
    sort_dict(field_data_dictionary, CFG_BIBSORT_WEIGHT_DISTANCE, run_sorting_for_rnk, sorting_locale)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/engine.py", line 407, in sort_dict
    sorted_records_list = sorted(dictionary, key=dictionary.__getitem__, cmp=locale.strcoll, reverse=False)
TypeError: coercing to Unicode: need string or buffer, list found
2015-02-06 13:20:56 --> Unexpected error occurred: coercing to Unicode: need string or buffer, list found.
2015-02-06 13:20:56 --> Traceback is:
2015-02-06 13:20:56 -->   File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsched/bibtask.py", line 615, in task_init
2015-02-06 13:20:56 -->     ret = _task_run(task_run_fnc)
2015-02-06 13:20:56 -->   File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsched/bibtask.py", line 1191, in _task_run
2015-02-06 13:20:56 -->     if callable(task_run_fnc) and task_run_fnc():
2015-02-06 13:20:56 -->   File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/daemon.py", line 366, in task_run_core
2015-02-06 13:20:56 -->     executed_correctly = rebalance(methods)
2015-02-06 13:20:56 -->   File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/daemon.py", line 173, in rebalance
2015-02-06 13:20:56 -->     return run_bibsort_rebalance(method_list)
2015-02-06 13:20:56 -->   File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/engine.py", line 913, in run_bibsort_rebalance
2015-02-06 13:20:56 -->     bibsort_methods[name]['washer'])
2015-02-06 13:20:56 -->   File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/engine.py", line 279, in run_sorting_method
2015-02-06 13:20:56 -->     sort_dict(field_data_dictionary, CFG_BIBSORT_WEIGHT_DISTANCE, run_sorting_for_rnk, sorting_locale)
2015-02-06 13:20:56 -->   File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/bibsort/engine.py", line 407, in sort_dict
2015-02-06 13:20:56 -->     sorted_records_list = sorted(dictionary, key=dictionary.__getitem__, cmp=locale.strcoll, reverse=False)
2015-02-06 13:20:56 --> Exiting
```

**Comment by jirikuncar** [comment]
> [ ] TypeError: coercing to Unicode: need string or buffer, list found
> [ ] Warning: Incorrect string value

@hachreak hopefully we can tackle these problems by porting the legacy code and using fully JSONAlchemy as source of our data.

**Comment by jirikuncar** [comment]
> - [ ] Warning: Incorrect string value

Can it be connected with #2981? (cc @jalavik)

**Comment by jalavik** [comment]
@jirikuncar It could be, but when looking around it could also be related to mysql table encoding issue: http://stackoverflow.com/questions/2108824/mysql-incorrect-string-value-error-when-save-unicode-string-in-django and http://stackoverflow.com/a/20349552
