### ISSUE TITLE
installation: error creating database with PostgreSQL

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#2799]
I executed the command:
```bash
inveniomanage database create
```
And with PostgreSQL, I have this error:

```python
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/bin/inveniomanage", line 9, in <module>
    load_entry_point('Invenio==1.9999.5.dev20150217155333', 'console_scripts', 'inveniomanage')()
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/base/manage.py", line 103, in main
    manager.run()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/ext/script/__init__.py", line 149, in __call__
    post_command.send(sender, args=args, **kwargs)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/ext/fixtures/__init__.py", line 53, in load_fixtures
    ).data(*fixtures.values()).setup()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/fixture/base.py", line 71, in setup
    self.loader.load(self.data)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/fixture/loadable/loadable.py", line 193, in load
    self.wrap_in_transaction(loader, unloading=False)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/fixture/loadable/loadable.py", line 310, in wrap_in_transaction
    routine()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/fixture/loadable/loadable.py", line 192, in loader
    self.load_dataset(ds)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/fixture/loadable/loadable.py", line 235, in load_dataset
    obj = ds.meta.storage_medium.save(row, column_vals())
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/fixture/loadable/sqlalchemy_loadable.py", line 235, in save
    setattr(obj, c, val)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/ext/hybrid.py", line 747, in __set__
    self.fset(instance, value)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/knowledge/models.py", line 68, in name
    self.slug = KnwKB.generate_slug(value)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/knowledge/models.py", line 204, in generate_slug
    KnwKB.slug.like(slug + '-%'),
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2682, in count
    return self.from_self(col).scalar()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2468, in scalar
    ret = self.one()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2437, in one
    ret = list(self)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2479, in __iter__
    self.session._autoflush()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1205, in _autoflush
    util.raise_from_cause(e)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1195, in _autoflush
    self.flush()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1916, in flush
    self._flush(objects)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2034, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1998, in _flush
    flush_context.execute()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 75, in save_obj
    mapper, table, insert)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 585, in _emit_insert_statements
    execute(statement, multiparams)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 800, in execute
    return meth(self, multiparams, params)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 897, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1029, in _execute_context
    context)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1232, in _handle_dbapi_exception
    exc_info
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 999, in _execute_context
    context)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 433, in do_executemany
    cursor.executemany(statement, parameters)
fixture.exc.LoadError: IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) insert or update on table "collection_field_fieldvalue" violates foreign key constraint "collection_field_fieldvalue_id_fieldvalue_fkey"
DETAIL:  Key (id_fieldvalue)=(0) is not present in table "fieldvalue".
 'INSERT INTO collection_field_fieldvalue (id_collection, id_field, id_fieldvalue, type, score, score_fieldvalue) VALUES (%(id_collection)s, %(id_field)s, %(id_fieldvalue)s, %(type)s, %(score)s, %(score_fieldvalue)s)' ({'score_fieldvalue': 0, 'id_field': 12, 'score': 10, 'id_fieldvalue': 0, 'id_collection': 1, 'type': 'soo'}, {'score_fieldvalue': 0, 'id_field': 2, 'score': 40, 'id_fieldvalue': 0, 'id_collection': 1, 'type': 'soo'}, {'score_fieldvalue': 0, 'id_field': 3, 'score': 30, 'id_fieldvalue': 0, 'id_collection': 1, 'type': 'soo'}, {'score_fieldvalue': 0, 'id_field': 6, 'score': 20, 'id_fieldvalue': 0, 'id_collection': 1, 'type': 'soo'}, {'score_fieldvalue': 2, 'id_field': 11, 'score': 5, 'id_fieldvalue': 25, 'id_collection': 2, 'type': 'seo'}, {'score_fieldvalue': 1, 'id_field': 11, 'score': 5, 'id_fieldvalue': 26, 'id_collection': 2, 'type': 'seo'}, {'score_fieldvalue': 0, 'id_field': 11, 'score': 5, 'id_fieldvalue': 32, 'id_collection': 2, 'type': 'seo'}, {'score_fieldvalue': 70, 'id_field': 2, 'score': 60, 'id_fieldvalue': 0, 'id_collection': 2, 'type': 'sew'}  ... displaying 10 of 106 total bound parameter sets ...  {'score_fieldvalue': 4, 'id_field': 7, 'score': 10, 'id_fieldvalue': 29, 'id_collection': 8, 'type': 'seo'}, {'score_fieldvalue': 2, 'id_field': 7, 'score': 10, 'id_fieldvalue': 30, 'id_collection': 8, 'type': 'seo'}) (with 'KnwKB_1' of '<fixture.dataset.dataset.KnwKB_1 object at 0x7fb63e53e810>' in <KnwKBData at 0x7fb63e2bb110 with keys ['KnwKB_1', 'KnwKB_2', 'KnwKB_3', 'KnwKB_4', 'KnwKB_5', 'KnwKB_6', 'KnwKB_7', 'KnwKB_8', 'KnwKB_9']>)
```

I tried to execute the same command with MySQL, but there isn't any `INSERT INTO collection_field_fieldvalue`!

Probably there is some consistency problem here: `invenio/modules/search/fixtures.py`.
The `id_fieldvalue` column is permitted to be `Null` by `nullable=True`, but, it seems that the default value is `0` instead `Null`.

**Comment by hachreak** [comment]
The `nullable=True` doesn't have effect. 
I tried to configure "manually" the field and PostgreSQL returns error:
`ERROR:  column "id_fieldvalue" is in a primary key`
