### ISSUE TITLE
legacy: run_sql problems with quotes

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#3089]
After 79741888d8e71b22e704a30038f9857d90a38590 there are several problems with running programs such as bibsched:

```shell
$ bibsched
...
File "/home/jlavik/envs/pu/src/invenio/invenio/legacy/dbquery_mysql.py", line 277, in run_sql
    except (OperationalError, InterfaceError):
NameError: global name 'OperationalError' is not defined
```
PS: Perhaps pylint -E could have catched this initial error?

I fixed the import, but for bibsched troubles were not over:

```
  File "/home/jlavik/envs/pu/src/invenio/invenio/legacy/bibsched/cli.py", line 378, in fetch_debug_mode
    r = run_sql('SELECT value FROM schSTATUS WHERE name = "debug_mode"')
  File "/home/jlavik/envs/pu/src/invenio/invenio/legacy/dbquery_mysql.py", line 277, in run_sql
    rc = cur.execute(sql, param)
  File "/home/jlavik/envs/pu/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/jlavik/envs/pu/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1054, "Unknown column 'debug_mode' in 'where clause'")
```

I tried fixing these, but its simply too much. Probably due to ansi mode quotes? I suggest in the meantime to revert 79741888d8e71b22e704a30038f9857d90a38590

@hachreak @jirikuncar

**Comment by hachreak** [comment]
Sorry, I replaced import in any files but I forgot to leave necessary in dbquery... T_T
I'll fix it immediately! :)

**Comment by hachreak** [comment]
for the `ansi_quote`: I think it's necessary to be compatible with PostgreSQL. T_T
Tomorrow I'll work on replace `"` with `'` in raw query on legacy code to solve the 2° problem...

**Comment by jalavik** [comment]
BTW, visiting the `/admin/` page gives the following error:

```
OperationalError: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'accROLE_accACTION_accARGUMENT.id' in 'field list'") [SQL: u'SELECT `accROLE_accACTION_accARGUMENT`.`id_accARGUMENT` AS `accROLE_accACTION_accARGUMENT_id_accARGUMENT`, `accROLE_accACTION_accARGUMENT`.id AS `accROLE_accACTION_accARGUMENT_id`, `accROLE_accACTION_accARGUMENT`.`id_accROLE` AS `accROLE_accACTION_accARGUMENT_id_accROLE`, `accROLE_accACTION_accARGUMENT`.`id_accACTION` AS `accROLE_accACTION_accARGUMENT_id_accACTION`, `accROLE_accACTION_accARGUMENT`.argumentlistid AS `accROLE_accACTION_accARGUMENT_argumentlistid` \nFROM `accROLE_accACTION_accARGUMENT` INNER JOIN `accARGUMENT` ON `accARGUMENT`.id = `accROLE_accACTION_accARGUMENT`.`id_accARGUMENT` \nWHERE `accROLE_accACTION_accARGUMENT`.argumentlistid > %s AND `accROLE_accACTION_accARGUMENT`.`id_accACTION` = %s'] [parameters: (0, 38L)]
```

**Comment by jirikuncar** [comment]
@jalavik can you be more specific? Do you have a full traceback?

**Comment by jalavik** [comment]
@jirikuncar Sure, all the admin sites are broken, including login.

* Go to http://0.0.0.0:4000/admin/ or try to login:
```
Traceback (most recent call last):
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jlavik/envs/pu/src/invenio/invenio/ext/legacy/__init__.py", line 120, in __call__
    response = self.app.handle_exception(e)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jlavik/envs/pu/src/invenio/invenio/ext/legacy/__init__.py", line 116, in __call__
    response = self.app.full_dispatch_request()
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/home/jlavik/envs/pu/src/invenio/invenio/base/wrappers.py", line 125, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/flask_admin/base.py", line 64, in inner
    abort = self._handle_view(f.__name__, **kwargs)
  File "/home/jlavik/envs/pu/src/invenio/invenio/ext/admin/views.py", line 76, in _handle_view
    if not current_user.is_authenticated():
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/flask_login.py", line 46, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/flask_login.py", line 794, in _get_user
    current_app.login_manager._load_user()
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/flask_login.py", line 363, in _load_user
    return self.reload_user()
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/flask_login.py", line 325, in reload_user
    user = self.user_callback(user_id)
  File "/home/jlavik/envs/pu/src/invenio/invenio/ext/login/__init__.py", line 180, in _load_user
    return UserInfo(int(uid))
  File "/home/jlavik/envs/pu/src/invenio/invenio/ext/login/legacy_user.py", line 84, in __init__
    acc = self._precache(data, force)
  File "/home/jlavik/envs/pu/src/invenio/invenio/ext/login/legacy_user.py", line 201, in _precache
    get_permitted_restricted_collections(user_info)
  File "/home/jlavik/envs/pu/src/invenio/invenio/modules/search/utils.py", line 196, in get_permitted_restricted_collections
    collection=restricted_collection_cache.cache
  File "/home/jlavik/envs/pu/src/invenio/invenio/modules/access/engine.py", line 57, in acc_authorize_action
    roles_list = acc_find_possible_roles(name_action, always_add_superadmin=True, batch_args=batch_args, **arguments)
  File "/home/jlavik/envs/pu/src/invenio/invenio/modules/access/control.py", line 1493, in acc_find_possible_roles
    id_action=id_action
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2398, in all
    return list(self)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2515, in __iter__
    return self._execute_and_instances(context)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2530, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1339, in _handle_dbapi_exception
    exc_info
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/jlavik/envs/pu/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (_mysql_exceptions.OperationalError) (1054, "Unknown column 'accROLE_accACTION_accARGUMENT.id' in 'field list'") [SQL: u'SELECT `accROLE_accACTION_accARGUMENT`.`id_accARGUMENT` AS `accROLE_accACTION_accARGUMENT_id_accARGUMENT`, `accROLE_accACTION_accARGUMENT`.id AS `accROLE_accACTION_accARGUMENT_id`, `accROLE_accACTION_accARGUMENT`.`id_accROLE` AS `accROLE_accACTION_accARGUMENT_id_accROLE`, `accROLE_accACTION_accARGUMENT`.`id_accACTION` AS `accROLE_accACTION_accARGUMENT_id_accACTION`, `accROLE_accACTION_accARGUMENT`.argumentlistid AS `accROLE_accACTION_accARGUMENT_argumentlistid` \nFROM `accROLE_accACTION_accARGUMENT` INNER JOIN `accARGUMENT` ON `accARGUMENT`.id = `accROLE_accACTION_accARGUMENT`.`id_accARGUMENT` \nWHERE `accROLE_accACTION_accARGUMENT`.argumentlistid > %s AND `accROLE_accACTION_accARGUMENT`.`id_accACTION` = %s'] [parameters: (0, 38L)]
```

**Comment by jacquerie** [comment]
I have a theory: https://github.com/inveniosoftware/invenio/blob/master/invenio/legacy/miscutil/sql/tabcreate.sql#L3713-L3721 creates a `accROLE_accACTION_accARGUMENT` with no `id` field, which is instead declared in its model: https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/access/models.py#L183.

Deleting those lines in `tabcreate.sql` fixes the problem, but I'm not sure if it is the right fix.

**Comment by jirikuncar** [comment]
> https://github.com/inveniosoftware/invenio/blob/master/invenio/legacy/miscutil/sql/tabcreate.sql#L3713-L3721

That file is never used ...

**Comment by hachreak** [comment]
@jalavik please, can you recreate the database with latest version of invenio master? :)
Maybe we already fix the problem.

**Comment by jacquerie** [comment]
Uh, after updating to latest master it works. The fact is, this was the table structure before:
```
mysql> show columns from accROLE_accACTION_accARGUMENT;
+----------------+------------------+------+-----+---------+-------+
| Field          | Type             | Null | Key | Default | Extra |
+----------------+------------------+------+-----+---------+-------+
| id_accROLE     | int(15) unsigned | NO   | PRI | 0       |       |
| id_accACTION   | int(15) unsigned | NO   | PRI | 0       |       |
| id_accARGUMENT | int(15)          | NO   | PRI | 0       |       |
| argumentlistid | mediumint(8)     | NO   | PRI | 0       |       |
+----------------+------------------+------+-----+---------+-------+
4 rows in set (0.00 sec)
```
and this is what I have now:
```
mysql> mysql> show columns from accROLE_accACTION_accARGUMENT;
+----------------+------------------+------+-----+---------+----------------+
| Field          | Type             | Null | Key | Default | Extra          |
+----------------+------------------+------+-----+---------+----------------+
| id             | int(15) unsigned | NO   | PRI | NULL    | auto_increment |
| id_accROLE     | int(15) unsigned | YES  | MUL | NULL    |                |
| id_accACTION   | int(15) unsigned | YES  | MUL | NULL    |                |
| id_accARGUMENT | int(15)          | YES  | MUL | NULL    |                |
| argumentlistid | mediumint(8)     | YES  |     | NULL    |                |
+----------------+------------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)
```

**Comment by jirikuncar** [comment]
I'm going to remove legacy sql scripts in order to avoid confusion.  (see #3102)

**Comment by jalavik** [comment]
@hachreak @jirikuncar So recreating the database may make it work, but it is not really the ideal solution. What about other Invenio instances upgrading with their precious data? So we would need to create a new upgrade script, I guess, to add the id column.

**Comment by jirikuncar** [comment]
@hachreak it was introduced in 79741888. Can you create an upgrade recipe?

**Comment by jirikuncar** [comment]
@hachreak is there still something blocking 2.1 release related to this issue?

**Comment by jalavik** [comment]
There is a related issue with exception handling in `run_sql()`. I've been trying this patch out and it seems to work: https://github.com/inspirehep/invenio/commit/14baf35144eb269ce35f8be7a1310728586a0827

PR will be incoming tomorrow.

**Comment by hachreak** [comment]
Until now I didn't  heard anyone that have this kind of problems with quoting.
maybe @jalavik can say us something more... :)

**Comment by jacquerie** [comment]
The following `ag` reveals a few more instances of unquoted table names (with some false positives): `$ ag --python -i "run_sql\(.*\s+from\s+[^\"]"`. In particular we have:
```
$ ag --python -i -l "run_sql\(.*\s+from\s+[^\"]" | wc -l
126
```

**Comment by hachreak** [comment]
Only names with uppercase inside explicitly require quoting.

e.g.
```sql
SELECT * FROM fuubar
```
Doesn't require.
```sql
SELECT * FROM fuuBar
```
It requires quoting as `SELECT * FROM fuuBar`.

**Comment by jacquerie** [comment]
Yes, that query has a lot of false positives, but a few hits as well: https://github.com/inveniosoftware/invenio/blob/0127513fd85bf5e9eeb8281957e10e2bb343ba10/invenio/modules/sequencegenerator/backend.py#L50

**Comment by hachreak** [comment]
:+1: can you catch with `ag` only which contain at least one uppercase char? :)

**Comment by jacquerie** [comment]
Maybe this? `ag --python "run_sql\(.*\s+(from|FROM)\s+[^\"][a-z]+[A-Z]+"` (63 results)

**Comment by hachreak** [comment]
Thanks! I'm fixing now this results... ;)

**Comment by jacquerie** [comment]
BTW: @jirikuncar told me that migrating the various upgrade recipes isn't important, so we don't need to care about those.

**Comment by hachreak** [comment]
yes! :dancer:

**Comment by jacquerie** [comment]
Just noticed that this affects column names as well, for example: https://github.com/inveniosoftware/invenio/blob/0127513fd85bf5e9eeb8281957e10e2bb343ba10/invenio/legacy/oairepository/updater.py#L76.

A simple regex to find some of these: `ag --python "run_sql\(\s*.*\s+(where|WHERE)\s+[^\"][a-z\_]+[A-Z]+"`.

BTW, I'm using `inveniomanage demosite populate --packages=invenio_demosite.base --yes-i-know` as a primitive integration testing. Is there something better to use?

**Comment by hachreak** [comment]
yes, I wrote all incompatibilities here: https://github.com/inveniosoftware/invenio/issues/3079

```
DB run_sql problems #3089 (legacy: tables name and columns name that have
upper case on sql queries require double quote, values in query require single
quote, table user require double quote)
```

**Comment by hachreak** [comment]
@jalavik can we close the issue? :)

**Comment by jalavik** [comment]
@hachreak Err. Probably :+1:  Thanks for all the fixes!
