### ISSUE TITLE
PostgreSQL: access module assignes -1 to a foreign key

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#3099]
On `database create` with PostgreSQL I have a problem to resolve:

```python
INFO in dbquery_postgresql [/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/dbquery_postgresql.py:114]:
INSERT INTO "accROLE_accACTION_accARGUMENT" ("id_accROLE",
                "id_accACTION" , "id_accARGUMENT", argumentlistid)
                VALUES (%s, %s, -1, -1) 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/bin/webaccessadmin", line 9, in <module>
    load_entry_point('invenio==2.1.0.dev20150305', 'console_scripts', 'webaccessadmin')()
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/base/helpers.py", line 50, in decorated_func
    result = f(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/access/scripts/webaccessadmin.py", line 111, in main
    DEF_DEMO_ROLES, DEF_DEMO_AUTHS)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/access/control.py", line 1913, in acc_add_default_settings
    **args)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/access/control.py", line 541, in acc_add_authorization
    VALUES (%s, %s, -1, -1) """, (id_role, id_action))
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/legacy/dbquery_postgresql.py", line 118, in run_sql
    cur = engine.execute(sql, (param, ))
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1986, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 906, in execute
    return self._execute_text(object, multiparams, params)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
    statement, parameters
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1339, in _handle_dbapi_exception
    exc_info
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) insert or update on table "accROLE_accACTION_accARGUMENT" violates foreign key constraint "accROLE_accACTION_accARGUMENT_id_accARGUMENT_fkey"
DETAIL:  Key (id_accARGUMENT)=(-1) is not present in table "accARGUMENT".
 [SQL: 'INSERT INTO "accROLE_accACTION_accARGUMENT" ("id_accROLE",\n                "id_accACTION" , "id_accARGUMENT", argumentlistid)\n                VALUES (%s, %s, -1, -1) '] [parameters: (6, 51)]
ERROR: failed execution of /home/vagrant/.virtualenvs/invenio2/bin/webaccessadmin -u admin -c -a -D
```

Access module try to put -1 on column `id_accARGUMENT` of the table `accROLE_accACTION_accARGUMENT`.
But it's a column that contains a Foreign Key!
So, PostgreSQL refuses to execute the query... T_T

I have 2 possibility to fix the problem:

1. Remove the Foreign Key from column `id_accARGUMENT` (easy way)
2. Find and substitute `-1` with None in `invenio/modules/access/control.py` (it's full of `run_sql`)

Which it's the best way? 

p.s. considering that I think `access` module requires a heavy refactoring.

cc @jirikuncar

**Comment by tiborsimko** [comment]
Considering there is no immediate plans to refactor access, @hachreak please look at fixing SQL queries (even at the price of removing foreign key!) so that the work on PostgreSQL can move forward.

**Comment by kaplun** [comment]
I am not sure if `accROLE_accACTION_accARGUMENT.id_accARGUMENT` should a foreign key at all. `id_accARGUMENT` identifies a possible group or rows within `accARGUMENT` having the same `id` (hence the `id` is not even a primary key). Additionally it has the special value `-1` to mean no argument.

So we could simply drop the `foreign key` property, or transform the code so that whenever `-1` is used it is substitute with `NULL`.
