### ISSUE TITLE
formatter: RegistryError Namespace format_elements already taken

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3127]
Using the latest `master` code, when accessing pages where formatter needs to be used (search results, holding pen entries) the following error appears on **the first request to the server**:

```python
Traceback (most recent call last):
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/src/invenio/invenio/ext/legacy/__init__.py", line 123, in __call__
    response = self.app.handle_exception(e)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/src/invenio/invenio/ext/legacy/__init__.py", line 119, in __call__
    response = self.app.full_dispatch_request()
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/src/invenio/invenio/base/wrappers.py", line 133, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/src/invenio/invenio/modules/workflows/views/holdingpen.py", line 173, in details
    formatted_data = bwobject.get_formatted_data(of)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/src/invenio/invenio/modules/workflows/models.py", line 395, in get_formatted_data
    of=of
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/src/inspire/inspire/modules/deposit/workflows/literature.py", line 225, in formatter
    xml_record=marcxml
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/src/invenio/invenio/modules/formatter/__init__.py", line 85, in format_record
    **kwargs)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/src/invenio/invenio/modules/formatter/engine.py", line 495, in format_record_1st_pass
    **kwargs)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/src/invenio/invenio/modules/formatter/engine.py", line 378, in format_record
    template, bfo, verbose=verbose, extra_context=kwargs)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/src/invenio/invenio/modules/formatter/engine.py", line 666, in format_with_format_template
    ctx = TEMPLATE_CONTEXT_FUNCTIONS_CACHE.functions
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/werkzeug/utils.py", line 71, in __get__
    value = self.func(obj)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/src/invenio/invenio/modules/formatter/engine.py", line 260, in functions
    for name in self.bibformat_elements().keys())
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/src/invenio/invenio/utils/memoise.py", line 50, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/src/invenio/invenio/modules/formatter/engine.py", line 219, in bibformat_elements
    for m in modules:
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/werkzeug/local.py", line 369, in <lambda>
    __iter__ = lambda x: iter(x._get_current_object())
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/flask_registry/base.py", line 219, in _lookup
    {namespace: registry_class(*args, **kwargs)}
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.py", line 561, in update
    self[key] = other[key]
  File "/Users/jmartinm/.virtualenvs/invenio-inspire/lib/python2.7/site-packages/flask_registry/base.py", line 121, in __setitem__
    raise RegistryError("Namespace %s already taken." % key)
RegistryError: Namespace format_elements already taken.
```

Refreshing the page makes it go away. Any hint of what might be the problem?

**Comment by jmartinm** [comment]
Closing it for the moment as it seemed to be generated by adding some legacy bft files in the overlay.
