### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#3192]
Recently, on our Invenio master staging servers we have seen a rise in exceptions related to the database connection. So called, `MySQL server has gone away` exceptions. I believe @egabancho has seen the same on the CDS Labs instances.

After a lot of back and forth on tuning with timeout parameters, we seem to have found some compromise on INSPIRE QA (at least no errors in the last 24 hours). However, we are running with fairly aggressive timeout settings in `wait_timeout=120` in MySQL and in SQLAlchemy `SQLALCHEMY_POOL_RECYCLE=60`. `CFG_MISCUTIL_SQL_USE_SQLALCHEMY` remains `False`. We'll experiment if we can further increase the timeouts and remain stable (we are running 10.0.19 MariaDB Server).

I bring this up, as it may be of interest to the community and to raise some questions on how this happens and since I suspect the legacy connection handling to be the culprit. If that is the case, it would be nice to understand which modules we can port/disable sooner rather than later to avoid legacy queries.

Here is a sample traceback:
```
Traceback (most recent call last):
  File "/opt/inspire/src/invenio/invenio/ext/legacy/__init__.py", line 119, in __call__
    response = self.app.full_dispatch_request()
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/inspire/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/opt/inspire/src/invenio/invenio/base/wrappers.py", line 133, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/opt/inspire/src/invenio/invenio/ext/babel/__init__.py", line 101, in set_translations
    g.ln = get_locale()
  File "/opt/inspire/src/invenio/invenio/ext/babel/selectors.py", line 40, in get_locale
    user_language = current_user.get('language')
  File "/opt/inspire/lib/python2.7/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/inspire/lib/python2.7/site-packages/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/opt/inspire/lib/python2.7/site-packages/flask_login.py", line 46, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/opt/inspire/lib/python2.7/site-packages/flask_login.py", line 794, in _get_user
    current_app.login_manager._load_user()
  File "/opt/inspire/lib/python2.7/site-packages/flask_login.py", line 357, in _load_user
    return self._load_from_cookie(request.cookies[cookie_name])
  File "/opt/inspire/lib/python2.7/site-packages/flask_login.py", line 409, in _load_from_cookie
    self.reload_user()
  File "/opt/inspire/lib/python2.7/site-packages/flask_login.py", line 325, in reload_user
    user = self.user_callback(user_id)
  File "/opt/inspire/src/invenio/invenio/ext/login/__init__.py", line 180, in _load_user
    return UserInfo(int(uid))
  File "/opt/inspire/src/invenio/invenio/ext/login/legacy_user.py", line 85, in __init__
    acc = self._precache(data, force)
  File "/opt/inspire/src/invenio/invenio/ext/login/legacy_user.py", line 202, in _precache
    get_permitted_restricted_collections(user_info)
  File "/opt/inspire/src/invenio/invenio/modules/search/utils.py", line 189, in get_permitted_restricted_collections
    restricted_collection_cache.recreate_cache_if_needed()
  File "/opt/inspire/src/invenio/invenio/legacy/miscutil/data_cacher.py", line 131, in recreate_cache_if_needed
    return self._cache.recreate_cache_if_needed()
  File "/opt/inspire/src/invenio/invenio/legacy/miscutil/data_cacher.py", line 81, in recreate_cache_if_needed
    if self.timestamp_verifier() > self.timestamp:
  File "/opt/inspire/src/invenio/invenio/modules/collections/cache.py", line 145, in timestamp_verifier
    return max(get_table_update_time('accROLE_accACTION_accARGUMENT'),
  File "/opt/inspire/src/invenio/invenio/legacy/dbquery_mysql.py", line 465, in get_table_update_time
    run_on_slave=run_on_slave)
  File "/opt/inspire/src/invenio/invenio/legacy/dbquery_mysql.py", line 290, in run_sql
    rc = cur.execute(sql, param)
  File "/opt/inspire/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/inspire/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (2006, 'MySQL server has gone away')
```

@jmartinm @kaplun @egabancho

**Comment by jalavik** [comment]
It's been a while since this issue have appeared. Closing for now.
