### ISSUE TITLE
workflows: UUID upgrade problem

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio#3288]
The change to using UUID type and the following upgrade script introduced in https://github.com/inveniosoftware/invenio/commit/e8f6551d9787ceec99248b2b0ad04b8f22a0d8b4 causes a problem with truncated values for the existing values - essentially corrupting the data (observed locally):
```
>>> Applying workflows_2015_06_05_resize_uuid_columns (Resize uuid columns on workflows tables.)
>>> workflows_2015_06_05_resize_uuid_columns: WARNING: Data truncated for column 'uuid' at row 1
>>> workflows_2015_06_05_resize_uuid_columns: WARNING: Data truncated for column 'uuid' at row 2
...
```
Before the uuid column was `db.String(36)` and a value included hyphens `00011d78-fd76-11e4-b9a6-ecf4bb24`. With the UUID type on MySQL, the hyphens are not considered and the length of the CHAR type is set to 32. During the upgrade the data is still stored with hyphens causing the truncation. 

I noticed this in the output of the upgrade, the corrupt IDs then cause a range of [troubles](https://gist.github.com/anonymous/53c521015b0c34685173) post-upgrade.

I suggest we either (a) change the MySQL type to `CHAR(36)`, or (b) remove hyphens from the data during upgrade.

EDIT: Considering changing a primary key is never a good idea, I suggest (a).

@hachreak @jirikuncar

**Comment by hachreak** [comment]
I changed because sometimes it's used `string` and sometimes it's used `UUID` object to represent a uuid.
It's ok for mysql, because we represent a uuid as a [CHAR](https://github.com/inveniosoftware/invenio/blob/master/invenio/ext/sqlalchemy/types/guid.py#L36).
But, with PostgreSQL is a problem to mix UUID and strings.

**Comment by jalavik** [comment]
Yeah, except now on MySQL the length of the uuid column CHAR is 32 instead of 36 which truncates existing data.

What do you think about changing the GUID type to have an hyphenate option similar to https://github.com/dcramer/django-uuidfield/blob/master/uuidfield/fields.py#L54-L59

Then for workflows models, we enable this hyphenate option but it is `False` by default.

```python
# invenio/ext/sqlalcemy/types/guid.py
    def load_dialect_impl(self, dialect):
        """Load dialect dependent implementation of UUID."""
        if dialect.name == 'postgresql':
            return dialect.type_descriptor(UUID())
        elif self.hyphenate:
            # UUID is stored with hyphens.
            return dialect.type_descriptor(CHAR(36))
        else:
            # UUID is stored as hex.
            return dialect.type_descriptor(CHAR(32))
```

**Comment by jirikuncar** [comment]
IMHO we should fix the upgrade recipe to process the string UUID to hex version.

**Comment by jalavik** [comment]
@jirikuncar We could, but it may be potentially risky data migration (for MySQL only) since changing the primary key is non-trivial. Either by removing and re-adding all rows in the bwlWORKFLOW table and then update any related tables (bwlOBJECT, bwlWORKFLOWLOGGING). Or do a series of steps to remove primary key index, update values, and re-add primary key index, in addition to updating related tables. Probably latter is easier.

In the end  it will involve a possibly risky data migration when upgrading production sites such as INSPIRE Labs and Zenodo which relies heavily on this data through submissions. I am not saying it's wrong to do it, but we should think a bit about it.

CC @lnielsen

**Comment by hachreak** [comment]
Currently, the GUID (UUID) field is used by 2 modules:
 - documents
 - workflows

**Comment by hachreak** [comment]
Or, another solution can be (maybe more easy):
- revert uuid and id_worflow fields as string(XX)
- take care to translate python UUID object to strings (e.g. in this [testsuite](https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/workflows/testsuite/test_workflows.py#L233))

**Comment by hachreak** [comment]
This is a error if I run tests using uuid as string with postgresql:

```python
--------------------------------------------------------------------------------
ERROR in wrappers [/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/ext/logging/wrappers.py:310]:

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/ext/legacy/__init__.py", line 110, in __call__
    response = self.app.full_dispatch_request()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/base/wrappers.py", line 133, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/deposit/views/deposit.py", line 75, in inner
    return f(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/deposit/views/deposit.py", line 313, in run
    return deposition.run_workflow()
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/deposit/models.py", line 1170, in run_workflow
    self.engine = self.type.run_workflow(self)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/deposit/models.py", line 485, in run_workflow
    module_name="webdeposit"
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/workflows/models.py", line 632, in start_workflow
    return start_func(workflow_name, data=[self], **kwargs)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/workflows/api.py", line 99, in start
    return run_worker(workflow_name, data, **kwargs)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/workflows/worker_engine.py", line 42, in run_worker
    engine = BibWorkflowEngine(wname, **kwargs)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/workflows/engine.py", line 133, in __init__
    if text_type(self.db_obj.uuid) not in self.log.name:
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 573, in get
    value = state._load_expired(state, passive)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 480, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 655, in load_scalar_attributes
    only_load_props=attribute_names)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 217, in load_on_ident
    return q.one()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2472, in one
    ret = list(self)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2515, in __iter__
    return self._execute_and_instances(context)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2530, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: character varying = uuid
LINE 3: WHERE "bwlWORKFLOW".uuid = '797b4114-15b9-11e5-8d9d-080027be...
                                 ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
 [SQL: 'SELECT "bwlWORKFLOW".uuid AS "bwlWORKFLOW_uuid", "bwlWORKFLOW".name AS "bwlWORKFLOW_name", "bwlWORKFLOW".created AS "bwlWORKFLOW_created", "bwlWORKFLOW".modified AS "bwlWORKFLOW_modified", "bwlWORKFLOW".id_user AS "bwlWORKFLOW_id_user", "bwlWORKFLOW"._extra_data AS "bwlWORKFLOW__extra_data", "bwlWORKFLOW".status AS "bwlWORKFLOW_status", "bwlWORKFLOW".current_object AS "bwlWORKFLOW_current_object", "bwlWORKFLOW".counter_initial AS "bwlWORKFLOW_counter_initial", "bwlWORKFLOW".counter_halted AS "bwlWORKFLOW_counter_halted", "bwlWORKFLOW".counter_error AS "bwlWORKFLOW_counter_error", "bwlWORKFLOW".counter_finished AS "bwlWORKFLOW_counter_finished", "bwlWORKFLOW".module_name AS "bwlWORKFLOW_module_name" \nFROM "bwlWORKFLOW" \nWHERE "bwlWORKFLOW".uuid = %(param_1)s'] [parameters: {'param_1': UUID('797b4114-15b9-11e5-8d9d-080027bebe68')}]
```

**Comment by jirikuncar** [comment]
> revert uuid and id_worflow fields as string(XX)

I would go for this fast solution and prepare better upgrade recipe together with @lnielsen and @jalavik.

**Comment by lnielsen** [comment]
I agree with @jalavik that the risk of data loss is too big without extensive testing on real data, so I prefer reverting to string(36) and let workflows module stay with that.

**Comment by hachreak** [comment]
@jirikuncar @jalavik there is some reason why it's a String(255) instead of String(36) [here](https://github.com/inveniosoftware/invenio/blob/9562937188cd2181e4b971a137ad56f01c33c414/invenio/modules/workflows/models.py#L903) ?

**Comment by jalavik** [comment]
@hachreak No, I don't think so. Indeed this should be String(36).
