### ISSUE TITLE
accounts: userEXT id as VARBINARY

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3290]
In the userEXT table, the ```id``` is created as ```db.VARBINARY```

https://github.com/inveniosoftware/invenio/blob/master/invenio/modules/accounts/models.py#L426

That seems to be the only occurrence of ```db.VARBINARY``` in Invenio and does not make much sense as that column holds ```Strings```. I just realised about it because I am having problems interacting with that column with an external MySQL editor like MySQL Workbench.

Would it make sense to change it to ```db.String``` ?

**Comment by jirikuncar** [comment]
:+1:

**Comment by jmartinm** [comment]
How are we using ```alembic``` at the moment? 

Is it possible to change the model from:

```
id = db.Column(db.VARBINARY(255), primary_key=True, nullable=False)
```

to

```
id = db.Column(db.String(255), primary_key=True, nullable=False)
```

And have the migration recipe be generated for me?

**Comment by jirikuncar** [comment]
@jmartinm `inveniomanage upgrader create recipe -a` might help a bit ...

**Comment by hachreak** [comment]
maybe if you set as normal string, then #3274 will not be necessary.. :)

**Comment by jmartinm** [comment]
> maybe if you set as normal string, then line will not be necessary.. :)

Nice. I am going to have a look now at this.

**Comment by jmartinm** [comment]
Just for reference, I changed the model to:

```python
id = db.Column(db.String(255), primary_key=True, nullable=False)
```

Then run:

```bash
$ inveniomanage upgrader create recipe -a -p invenio.modules.accounts
```

And the output file contains basically all the create statements of Invenio (not the migration of the column in question). Appearances of the `userEXT` table are:

```python
op.create_table('userEXT',
    db.Column('id', db.String(length=255), nullable=False),
    db.Column('method', db.String(length=50), nullable=False),
    db.Column('id_user', invenio.ext.sqlalchemy.types.legacyinteger.LegacyInteger(), nullable=False),
    db.ForeignKeyConstraint(['id_user'], [u'user.id'], ),
    db.PrimaryKeyConstraint('id', 'method'),
    mysql_charset='utf8',
    mysql_engine='MyISAM',
    sql_mode='ansi_quotes'
    )
```

```python
 op.create_index('id_user', 'userEXT', ['id_user', 'method'], unique=True)
```

Am I missing something regarding the migration command? Otherwise I will have to copy/paste and old migration and do it manually (which is a bit sad)

**Comment by jmartinm** [comment]
So @hachreak what was the problem with the mentioned [line](https://github.com/inveniosoftware/invenio/pull/3274/files#diff-6ffd71577ca22eab7dfaa7ad0bcc2704R128) ? For me with MySQL that statetement works fine with and without calling ```encode```. Was it a PostgreSQL problem?

Just trying to understand it to not break anything when changing that line

**Comment by jmartinm** [comment]
PR added.

**Comment by hachreak** [comment]
```python
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/ext/legacy/__init__.py", line 110, in __call__
    response = self.app.full_dispatch_request()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/base/wrappers.py", line 133, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/oauthclient/views/client.py", line 205, in disconnect
    return disconnect_handlers[remote_app]()
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/oauthclient/handlers.py", line 398, in inner
    return f(remote, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/oauthclient/contrib/orcid.py", line 141, in disconnect_handler
    oauth_unlink_external_id(dict(id=orcid, method='orcid'))
  File "/home/vagrant/.virtualenvs/invenio2/src/invenio/invenio/modules/oauthclient/utils.py", line 129, in oauth_unlink_external_id
    method=external_id['method']).delete()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2827, in delete
    delete_op.exec_()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1086, in exec_
    self._do_exec()
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1264, in _do_exec
    mapper=self.mapper)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1023, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1344, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/vagrant/.virtualenvs/invenio2/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
TypeError: can't escape unicode to binary
```

Inside Invenio we set VARBINARY as [BYTEA](https://github.com/inveniosoftware/invenio/blob/master/invenio/ext/sqlalchemy/__init__.py#L116).
Here you can find PostgreSQL [documentation](http://www.postgresql.org/docs/9.4/static/datatype-binary.html).

**Comment by jirikuncar** [comment]
> Inside Invenio we set `VARBINARY` as `BYTEA`.

Let's move all to `String`.

**Comment by jmartinm** [comment]
> Let's move all to String.

As far as I can see this is the only table that uses VARBINARY
