### ISSUE TITLE
global: inveniomanage database create fails

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#3406]
How to reproduce
==============

With Invenio `master` and Invenio-demosite `master`

```bash
$ inveniomanage database init --user=root --yes-i-know
```

```bash
$ inveniomanage database create
```

```python
>>> There are 5 tables to be loaded.
Traceback (most recent call last):
  File "/Users/jmartinm/.virtualenvs/invenio-demosite/bin/inveniomanage", line 9, in <module>
    load_entry_point('invenio==2.2.0.dev20150608', 'console_scripts', 'inveniomanage')()
  File "/Users/jmartinm/.virtualenvs/invenio-demosite/src/invenio/invenio/base/manage.py", line 103, in main
    manager.run()
  File "/Users/jmartinm/.virtualenvs/invenio-demosite/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/jmartinm/.virtualenvs/invenio-demosite/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/jmartinm/.virtualenvs/invenio-demosite/src/invenio/invenio/ext/script/__init__.py", line 179, in __call__
    post_command.send(sender, args=args, **kwargs)
  File "/Users/jmartinm/.virtualenvs/invenio-demosite/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/Users/jmartinm/.virtualenvs/invenio-demosite/src/invenio/invenio/modules/upgrader/__init__.py", line 82, in populate_existing_upgrades
    map(iu.register_success, iu.get_upgrades())
  File "/Users/jmartinm/.virtualenvs/invenio-demosite/src/invenio/invenio/modules/upgrader/engine.py", line 410, in get_upgrades
    self.order_upgrades(plugins, self.history))
  File "/Users/jmartinm/.virtualenvs/invenio-demosite/src/invenio/invenio/modules/upgrader/engine.py", line 497, in order_upgrades
    " upgrade %s" % (node_id, d))
RuntimeError: Upgrade invenio_2015_07_14_innodb depends on an unknown upgrade oaiharvester_2015_07_14_innodb
```

**Comment by jalavik** [comment]
Indeed it is because `invenio.modules.oaiharvester` was put in `PACKAGES_EXCLUDE` after c4eb545. After discussion with @jirikuncar we agreed to release the Invenio-OAIHarvester module to fix this issue.

Meanwhile, removing the module from the exclude list should fix the issue.

**Comment by jmartinm** [comment]
As discussed IRL with @jalavik , it is also necessary to add ``__init__.py`` in https://github.com/inveniosoftware/invenio/tree/master/invenio/modules/oaiharvester

**Comment by jirikuncar** [comment]
@jmartinm @jalavik @lnielsen what about just warning about missing 
```diff
diff --git a/invenio/modules/upgrader/engine.py b/invenio/modules/upgrader/engine.py
index 2a2ba49..f7c5b82 100644
--- a/invenio/modules/upgrader/engine.py
+++ b/invenio/modules/upgrader/engine.py
@@ -410,12 +410,13 @@ class InvenioUpgrader(object):
                                 self.order_upgrades(plugins, self.history))
         return self.upgrades
 
-    def _create_graph(self, upgrades, history={}):
+    def _create_graph(self, upgrades, history=None):
         """Create dependency graph from upgrades.
 
         @param upgrades: Dict of upgrades
         @param history: Dict of applied upgrades
         """
+        history = history or {}
         graph_incoming = {}  # nodes their incoming edges
         graph_outgoing = {}  # nodes their outgoing edges
 
@@ -450,7 +451,7 @@ class InvenioUpgrader(object):
 
         return endpoints
 
-    def order_upgrades(self, upgrades, history={}):
+    def order_upgrades(self, upgrades, history=None):
         """Order upgrades according to their dependencies.
 
         (topological sort using
@@ -459,6 +460,7 @@ class InvenioUpgrader(object):
         @param upgrades: Dict of upgrades
         @param history: Dict of applied upgrades
         """
+        history = history or {}
         graph_incoming, graph_outgoing = self._create_graph(upgrades, history)
 
         # Removed already applied upgrades (assumes all dependencies prior to
@@ -493,8 +495,8 @@ class InvenioUpgrader(object):
         for node_id, depends_on in graph_incoming.items():
             for d in depends_on:
                 if d not in graph_incoming:
-                    raise RuntimeError("Upgrade %s depends on an unknown"
-                                       " upgrade %s" % (node_id, d))
+                    warnings.warn("Upgrade %s depends on an unknown"
+                                  " upgrade %s" % (node_id, d))
 
         # Nodes with no incoming edges
         start_nodes = filter(lambda x: len(graph_incoming[x]) == 0,
```

**Comment by jalavik** [comment]
@jirikuncar :+1:

**Comment by lnielsen** [comment]
As discussed IRL with @jirikuncar:

1) Missing upgrades shouldn't happen (upgrades should only depend on upgrades in it's own module). Likely this is temporary problem, because of all the module externalisation happening these days. 
2) Missing upgrades usually means spelling mistake or similar in the depends on attribute, so normally we should bail out and not run the upgrades. 

Possible solutions:
1) Add an ``--ignore-missing`` option to run command
2) Add a ``mark as applied`` command + an apply command (i.e. run an upgrade plus anything it depends on).

**Comment by jalavik** [comment]
@lnielsen So the cross module upgrade dependency of the InnoDB upgrade kinda was the issue here together with externalisation.

This exception happens when building the demosite, via signals, so we could amend that trigger to use such an `ignore-missing` parameter to avoid interrupting demosite setup?
