### ISSUE TITLE
webstat: crash in webstat.modify_customevent

### ISSUE THREAD

**Issue by jmacmahon** [inveniosoftware/invenio#3421]
The function `webstat.modify_customevent` manages the `staEVENT` and `staEVENTxx` series of MySQL tables for logging custom events.  It is usally called by the script `webstatadmin`, which reads a config from `etc/webstat/webstat.cfg` to pass parameters to this function.

When the script is run on a clean DB, it functions well, but in the case of modifying the schema for existing custom events, it crashes with a `TypeError`.

## Environment
- Invenio `legacy`, (specifically commit 070d9be)
- Python `2.7.6`
- System: Ubuntu Trusty (`ubuntu/trusty64` Vagrant image), set up with `invenio_kickstart` script.

## Steps to reproduce
With a vanilla `legacy` installation, from `invenio_kickstart`:
```
vagrant@vagrant-ubuntu-trusty-64:/opt/invenio/bin$ # First run calls webstat.create_customevent
vagrant@vagrant-ubuntu-trusty-64:/opt/invenio/bin$ ./webstatadmin --load-config
vagrant@vagrant-ubuntu-trusty-64:/opt/invenio/bin$ # Second run calls webstat.modify_customevent
vagrant@vagrant-ubuntu-trusty-64:/opt/invenio/bin$ ./webstatadmin --load-config
Traceback (most recent call last):
  File "./webstatadmin", line 32, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/invenio/webstatadmin.py", line 59, in main
    task_run_fnc=task_run_core)
  File "/usr/local/lib/python2.7/dist-packages/invenio/bibtask.py", line 530, in task_init
    task_submit_check_options_fnc)
  File "/usr/local/lib/python2.7/dist-packages/invenio/bibtask.py", line 733, in _task_build_params
    if not task_submit_check_options_fnc():
  File "/usr/local/lib/python2.7/dist-packages/invenio/webstatadmin.py", line 213, in task_submit_check_options
    webstat.modify_customevent(name, cols=cols)
  File "/usr/local/lib/python2.7/dist-packages/invenio/webstat.py", line 617, in modify_customevent
    if not run_sql("SHOW TABLES LIKE %s", res[0][0]):
  File "/usr/local/lib/python2.7/dist-packages/invenio/dbquery.py", line 258, in run_sql
    rc = cur.execute(sql, param)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 187, in execute
    query = query % tuple([db.literal(item) for item in args])
TypeError: not all arguments converted during string formatting
```

Note that this is with no modifications to `webstat.cfg` at any point before or during the process.

**Comment by tiborsimko** [comment]
Hmm, the `webstatadmin --load-config` installation step is usually called only once.  (The thinking being "dump-and-load", "dump-and-load", etc.)  Is there a real-life use case for calling it twice?  

(this doesn't mean we shouldn't fix it...)
