### ISSUE TITLE
inveniomanage raise LookupError exception

### ISSUE THREAD

**Issue by jackyq2015** [inveniosoftware/invenio#3529]
(zenodo)ubuntu@ip-10-165-168-200:~/.virtualenvs/zenodo/src/invenio$ inveniomanage config create secret-key
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/zenodo/bin/inveniomanage", line 7, in <module>
    from invenio_base.manage import main
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/invenio_base/manage.py", line 28, in <module>
    manager = Manager(create_app(), with_default_commands=False)
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/invenio_base/factory.py", line 281, in create_app
    blueprints=BlueprintAutoDiscoveryRegistry(app=app),
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/flask_registry/registries/appdiscovery.py", line 260, in __init__
    silent=silent
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/flask_registry/registries/modulediscovery.py", line 254, in __init__
    self.discover(app=app)
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/flask_registry/registries/modulediscovery.py", line 175, in discover
    self._discover_module(pkg)
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/flask_registry/registries/appdiscovery.py", line 289, in _discover_module
    ).get(candidate.name)
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/flask/app.py", line 979, in add_url_rule
    self.url_map.add(rule)
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1128, in add
    rule.bind(self)
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/werkzeug/routing.py", line 622, in bind
    self.compile()
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/werkzeug/routing.py", line 672, in compile
    _build_regex(self.is_leaf and self.rule or self.rule.rstrip('/'))
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/werkzeug/routing.py", line 662, in _build_regex
    variable, converter, c_args, c_kwargs)
  File "/home/ubuntu/.virtualenvs/zenodo/local/lib/python2.7/site-packages/werkzeug/routing.py", line 630, in get_converter
    raise LookupError('the converter %r does not exist' % converter_name)
LookupError: the converter 'depositions' does not exist

(zenodo)ubuntu@ip-10-165-168-200:~/.virtualenvs/zenodo/src/invenio$ python --version
Python 2.7.6
(zenodo)ubuntu@ip-10-165-168-200:~/.virtualenvs/zenodo/src/invenio$ uname -a
Linux ip-10-165-168-200 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jirikuncar** [comment]
Add `'invenio_deposit.url_converters'` to `EXTENSIONS` in your overlay.

**Comment by jackyq2015** [comment]
could you please elaborate how to add it? I am not so familiar with Python.

**Comment by k3njiy** [comment]
I'm having the same problem here. Trying to setup invenio dev. Where do I have to add 'invenio_deposit.url_converters'? What file?

**Comment by egabancho** [comment]
For example this is what we have for the CDS overlay https://github.com/CERNDocumentServer/cds/blob/cdslabs/cds/config.py#L119

It is commented out because we don't have `invent_deposit` enabled just yet, in your case you need to uncomment it and it should be fine.
