### ISSUE TITLE
installation: utf-8 error when creating instance

### ISSUE THREAD

**Issue by jgarcial** [inveniosoftware/invenio#3712]
`UnicodeDecodeError` when running `inveniomanage instance create`

`Traceback (most recent call last):
  File "/home/garciaj/.virtualenvs/lens3/bin/inveniomanage", line 11, in <module>
    sys.exit(cli())
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/invenio_base/cli.py", line 48, in create
    'secret_key': secret_key,
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/cookiecutter/main.py", line 144, in cookiecutter
    output_dir=output_dir
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/cookiecutter/generate.py", line 350, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/cookiecutter/generate.py", line 168, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/home/garciaj/.virtualenvs/lens3/local/lib/python2.7/site-packages/jinja2/loaders.py", line 175, in get_source
    contents = f.read().decode(self.encoding)
  File "/home/garciaj/.virtualenvs/lens3/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf3 in position 1: invalid continuation byte`

**Comment by tiborsimko** [comment]
@jgarcial The Invenio demo site now works again without problems (if you try GitHub `master` branch). You can retry either Docker or Vagrant [demo instructions](http://invenio.readthedocs.io/en/latest/installation/installation-quick.html). Does it work for you? If so, you can compare `pip freeze` versions of Flask, Jinja and friends... Also, have you made any deep customisations regarding `lens3` overlay or were you running your `inveniomanage create` command relatively early on and pristine?
