### ISSUE TITLE
Installation - error with docker

### ISSUE THREAD

**Issue by suso2** [inveniosoftware/invenio#3714]
Hi. I have tried to install invenio 3 using docker. Every time the installation stops (docker-compose build): 

```
Installing collected packages: invenio-indexer, invenio-jsonschemas, invenio-marc21, invenio-oaiserver, invenio-search-ui, invenio3
  Running setup.py develop for invenio3
Successfully installed invenio-indexer-1.0.0a8 invenio-jsonschemas-1.0.0a3 invenio-marc21-1.0.0a3 invenio-oaiserver-1.0.0a8 invenio-search-ui-1.0.0a5 invenio3
Traceback (most recent call last):
  File "/home/invenio/.virtualenvs/invenio3/bin/invenio3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (elasticsearch 2.4.0 (/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages), Requirement.parse('elasticsearch<6.0.0,>=5.0.0'), set(['elasticsearch-dsl']))
ERROR: Service 'static' failed to build: The command '/bin/sh -c /code/scripts/create-instance.sh' returned a non-zero code: 1
```

**Comment by jacquerie** [comment]
Hi @suso2, thanks for filing this issue.

This issue is known, and is already being worked on here: https://github.com/inveniosoftware/invenio-search/pull/91.

**Comment by suso2** [comment]
Thanks!
is it possible to install Invenio 3 using other way? (I also have problems using kickstart scripts)
Next week I have to show several repository systems and Invenio is one of my favourite (I was able to install invenio 1.2.1 but I want to see the new features of Invenio 3).

Thanks again

**Comment by tiborsimko** [comment]
@suso2 https://github.com/inveniosoftware/invenio-search/pull/91 is merged now, but a new version needs to be released on PyPI still. You could try with `./scripts/create-instance.sh --devel` which will take the package from GitHub. 

We are probably going to pin some of the package dependencies so that the Invenio demo site would be easily installable even during these unstable "alpha" times... You may perhaps want to wait for that, since using GitHub packages may bring other issues...

**Comment by tiborsimko** [comment]
> You may perhaps want to wait for that, since using GitHub packages may bring other issues...

Indeed, if you try `--devel`, it will lead to Celery prerequisite version troubles: 

```
pkg_resources.ContextualVersionConflict: 
(celery 4.0.0 (/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages), 
Requirement.parse('celery<4.0,>=3.1'), set(['flask-celeryext']))
```

You may want to wait for dependency pinning...

**Comment by tiborsimko** [comment]
@nharraud Tested the newly released `invenio-search` over the weekend, and got into:

```console
$ docker-compose run --rm web ./scripts/populate-instance.sh
Creating database postgresql+psycopg2://invenio3:dbpass123@postgresql:5432/invenio3
Creating all tables!
  [####################################]  100%
Created all tables!
User created successfully.
{'active': True, 'password': '****', 'email': u'info@inveniosoftware.org'}
Creating indexes...
  [------------------------------------]    0%
Traceback (most recent call last):
  File "/home/invenio/.virtualenvs/invenio3/bin/invenio3", line 11, in <module>
    load_entry_point('invenio3', 'console_scripts', 'invenio3')()
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask/cli.py", line 229, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_search/cli.py", line 61, in init
    for name, response in bar:
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/_termui_impl.py", line 259, in next
    rv = next(self.iter)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_search/ext.py", line 158, in create
    for result in _create(self.aliases):
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_search/ext.py", line 148, in _create
    for result in _create(value, alias=name):
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_search/ext.py", line 148, in _create
    for result in _create(value, alias=name):
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_search/ext.py", line 145, in _create
    ignore=ignore,
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 71, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 107, in create
    params=params, body=body)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 80, in perform_request
    self.log_request_fail(method, url, response.request.path_url, body, time.time() - start, exception=e)
UnboundLocalError: local variable 'response' referenced before assignment
```

and I note lots of:

```
elasticsearch_1  | [2016-11-14T15:20:31,480][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [field_link_and_sequence_number]
elasticsearch_1  | [2016-11-14T15:20:31,480][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [report_number]
elasticsearch_1  | [2016-11-14T15:20:31,480][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [control_subfield]
elasticsearch_1  | [2016-11-14T15:20:31,480][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [place_publisher_and_date_of_publication]
elasticsearch_1  | [2016-11-14T15:20:31,480][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [main_entry_heading]
elasticsearch_1  | [2016-11-14T15:20:31,480][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [relationship_information]
elasticsearch_1  | [2016-11-14T15:20:31,480][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [series_data_for_related_item]
elasticsearch_1  | [2016-11-14T15:20:31,480][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [standard_technical_report_number]
elasticsearch_1  | [2016-11-14T15:20:31,480][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [international_standard_serial_number]
elasticsearch_1  | [2016-11-14T15:20:31,480][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [display_constant_controller]
elasticsearch_1  | [2016-11-14T15:20:31,480][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [coden_designation]
elasticsearch_1  | [2016-11-14T15:20:31,480][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [related_parts]
elasticsearch_1  | [2016-11-14T15:20:31,481][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [relationship_code]
elasticsearch_1  | [2016-11-14T15:20:31,481][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [qualifying_information]
elasticsearch_1  | [2016-11-14T15:20:31,481][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [physical_description]
elasticsearch_1  | [2016-11-14T15:20:31,481][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [uniform_title]
elasticsearch_1  | [2016-11-14T15:20:31,481][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [material_specific_details]
```

Looks like we may want to amend schemas mappings? 

P.S. This is with latest Elasticsearch (5.0.0) and:

```console 
$ docker exec -i -t inveniomaster_web_1 pip freeze | grep elastic
elasticsearch==5.0.1
elasticsearch-dsl==5.0.0
```

but I got similar issues when I tried to force both Python libraries to `<3.0.0,>=2.0.0'`.

**Comment by nharraud** [comment]
@tiborsimko There were some breaking changes for elasticsearch 5.0. I got one which was printing a similar message because of [this](https://github.com/inveniosoftware/invenio-search/commit/e9ef09f17ae6051aa1814d75ff0c2da0de33722c#diff-1a125e38ddde16703cca1bfcb3fe9942R131) ([elasticsearch doc explaining the issue](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_index_apis.html#_optype_create_without_an_id)). But I doubt that it is related as the test is now passing in invenio-search.

[elasticsearch.py has some ugly error handling](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/connection/http_requests.py#L80)  which makes it fail to display the proper error message.

My advice would be for now to use only elasticsearch <5 as it indeed require some mapping changes. Example: [it is now required to explicitly tell in the mapping which text fields will be used for sorting](https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html#_fielddata_is_disabled_on_literal_text_literal_fields_by_default). Which is why [this](https://github.com/inveniosoftware/invenio-search/commit/e9ef09f17ae6051aa1814d75ff0c2da0de33722c#diff-9d101cb685ee7bf7f81817f91ca679c4R7) is needed in invenio-search.

I tested invenio-search but I didn't check that every other module using it is working properly with ES 5.0.

**Comment by nharraud** [comment]
Also the elasticsearch-py and elasticsearch-dsl libraries' version now match the elasticsearch version they should be used with.
Thus their version `<3.0.0,>=2.0.0'` should only be used with elasticsearch 2.x (even if in practive using them with ES 5 seems to work for invenio-search).

**Comment by tiborsimko** [comment]
> My advice would be for now to use only elasticsearch <5 for now as it indeed requires some mapping changes.

OK, let's do that.  We can discuss at the forum whether we can stick with Elasticsearch 2 everywhere, whether anyone needs Elasticsearch 5 already now, and when would be a good time to recommend switching to Elasticsearch 5...

I made a quick PR to pin Elasticsearch version 2 for Docker based installations too, as it is already on version 2 for Vagrant.
