### ISSUE TITLE
installation: create-instance.sh exception

### ISSUE THREAD

**Issue by evelthon** [inveniosoftware/invenio#3753]
When executing create-instance.sh, command
_echo '{}' | jinja2 $scriptpathname/instance.cfg > ../../var/${INVENIO_WEB_INSTANCE}-instance/${INVENIO_WEB_INSTANCE}.cfg_ will throw an exception like below about pyyaml.

`Traceback (most recent call last):
  File "/home/invenio/.virtualenvs/invenio3/bin/jinja2", line 11, in <module>
    sys.exit(main())
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/jinja2cli/cli.py", line 335, in main
    sys.exit(cli(opts, args))
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/jinja2cli/cli.py", line 225, in cli
    raise InvalidDataFormat('%s: install pyyaml to fix' % format)
jinja2cli.cli.InvalidDataFormat: yaml: install pyyaml to fix`

**Comment by evelthon** [comment]
To overcome this, command `pip install jinja2-cli` should be replaced with `pip install jinja2-cli pyyaml`.
