### ISSUE TITLE
Cannot run docker container

### ISSUE THREAD

**Issue by Nnidyu** [inveniosoftware/invenio#3761]
Hi,

I am trying to build a docker container for testing using instructions for version 3.0: http://inveniosoftware.org/gettingstarted
I am using v3.0.0a4 as master did not work for me. I had to apply fixes mentioned in #3753 and #3737. However I have encountered a new problem:

```
$ docker-compose run --rm web ./scripts/populate-instance.sh 
Creating database postgresql+psycopg2://invenio3:dbpass123@postgresql:5432/invenio3
Creating all tables!
  [####################################]  100%
Created all tables!
User created successfully.
{'active': True, 'password': '****', 'email': u'info@inveniosoftware.org'}
Traceback (most recent call last):
  File "/home/invenio/.virtualenvs/invenio3/bin/invenio3", line 11, in <module>
    load_entry_point('invenio3', 'console_scripts', 'invenio3')()
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask/cli.py", line 374, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask/cli.py", line 251, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_records/cli.py", line 117, in create
    click.echo(Record.create(record, id_=id_).id)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_records/api.py", line 193, in create
    record.validate(**kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_records/api.py", line 140, in validate
    return _records_state.validate(self, self['$schema'], **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_records/ext.py", line 58, in validate
    **kwargs
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: [u'ALEPH Collaboration'] is not of type u'string'

Failed validating u'type' in schema[u'allOf'][9][u'properties'][u'added_entry_corporate_name'][u'items'][u'properties'][u'miscellaneous_information']:
    {u'type': u'string'}

On instance[u'added_entry_corporate_name'][0][u'miscellaneous_information']:
    [u'ALEPH Collaboration']
```

**Comment by dinosk** [comment]
This is due to the outdated bd-v1.0.0.json schema in populate-instance.sh. There is a new version bd-v1.0.2.json and it will be updated soon.

**Comment by nharraud** [comment]
Another fix is on its way in dojson for inveniosoftware/dojson#189. The docker container will not work until it is also released.

**Comment by tiborsimko** [comment]
@Nnidyu The installation problem has been fixed yesterday.  Please just use the `master` branch.

```console
$ git clone https://github.com/inveniosoftware/invenio
$ cd invenio/
$ docker-compose build
$ docker-compose up
$ docker-compose run --rm web ./scripts/populate-instance.sh
$ firefox http://127.0.0.1/records/1
```
