### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by heidricha** [inveniosoftware/invenio#3766]
docker-compose build ends up with en error:

Collect static from blueprints.
Copied: [invenio_search_ui] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/scss/invenio_search_ui/search.scss'
Copied: [invenio_search_ui] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/templates/invenio_search_ui/count.html'
Copied: [invenio_search_ui] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/templates/invenio_search_ui/loading.html'
Copied: [invenio_search_ui] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/templates/invenio_search_ui/togglebutton.html'
Copied: [invenio_search_ui] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/templates/invenio_search_ui/error.html'
Copied: [invenio_search_ui] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/templates/invenio_search_ui/searchbar.html'
Copied: [invenio_search_ui] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/templates/invenio_search_ui/selectbox.html'
Copied: [invenio_search_ui] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/templates/invenio_search_ui/pagination.html'
Copied: [invenio_search_ui] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/templates/invenio_search_ui/marc21/default.html'
Copied: [invenio_search_ui] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/js/invenio_search_ui/app.js'
Copied: [invenio_i18n] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/js/invenio_i18n/angularLangSelector.js'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/scss/invenio_theme/header.scss'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/scss/invenio_theme/styles.scss'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/scss/invenio_theme/input-icon.scss'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/scss/invenio_theme/variables.scss'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/scss/invenio_theme/body.scss'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/scss/invenio_theme/cover.scss'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/scss/invenio_theme/navbar.scss'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/scss/invenio_theme/type.scss'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/scss/invenio_theme/admin.scss'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/scss/invenio_theme/footer.scss'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/images/invenio-black.svg'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/images/invenio-color.svg'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/images/invenio-white.svg'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/js/base.js'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/js/build.js'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/js/settings.js'
Copied: [invenio_theme] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/js/invenio_theme/admin.js'
Copied: [invenio_oaiserver] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/xsl/MARC21slim2OAIDC.xsl'
Copied: [invenio_oaiserver] '/home/invenio/.virtualenvs/invenio3/var/invenio3-instance/static/xsl/oai2.v1.0.xsl'
Building bundle: gen/search.%(version)s.js
Building bundle: gen/styles.%(version)s.css
Traceback (most recent call last):
  File "/home/invenio/.virtualenvs/invenio3/bin/invenio3", line 11, in <module>
    load_entry_point('invenio3', 'console_scripts', 'invenio3')()
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask/cli.py", line 374, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask/cli.py", line 251, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask_assets.py", line 492, in build
    _webassets_cmd('build')
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask_assets.py", line 480, in _webassets_cmd
    getattr(cmdenv, cmd)()
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/webassets/script.py", line 172, in __call__
    bundle.build(force=True, disable_cache=no_cache)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/webassets/bundle.py", line 682, in build
    disable_cache=disable_cache))
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/webassets/bundle.py", line 619, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/webassets/bundle.py", line 543, in _merge_and_apply
    kwargs=item_data)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/webassets/merge.py", line 276, in apply
    return self._wrap_cache(key, func)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/webassets/merge.py", line 218, in _wrap_cache
    content = func().getvalue()
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/webassets/merge.py", line 251, in func
    getattr(filter, type)(data, out, **kwargs_final)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_assets/filters.py", line 105, in input
    args = [self.binary or 'cleancss'] + self.rebase_opt
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_assets/filters.py", line 98, in rebase_opt
    ['cleancss', '--version'], stdout=PIPE).communicate()
  File "/usr/local/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ERROR: Service 'static' failed to build: The command '/bin/sh -c /code/scripts/create-instance.sh' returned a non-zero code: 1

any idea?

**Comment by heidricha** [comment]
looks like it has been solved earlier, just searching took a long time for me:

updated provision-web script made my day! 

line 139: $sudo su -c "npm install -g node-sass@3.8.0 clean-css@3.4.24 requirejs uglify-js"
