### ISSUE TITLE
TypeError: <LocalProxy unbound> is not a Python function

### ISSUE THREAD

**Issue by astrofrog** [inveniosoftware/invenio#3809]
I'm getting an exception when trying to run:

```
$ inveniomanage config set create secret-key
Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/asclepias/bin/inveniomanage", line 11, in <module>
    sys.exit(main())
  File "/Users/tom/miniconda3/envs/asclepias/lib/python2.7/site-packages/invenio_base/manage.py", line 102, in main
    register_manager(manager)
  File "/Users/tom/miniconda3/envs/asclepias/lib/python2.7/site-packages/invenio_ext/script/__init__.py", line 331, in register_manager
    collect.init_script(manager)
  File "/Users/tom/miniconda3/envs/asclepias/lib/python2.7/site-packages/flask_collect/collect.py", line 119, in init_script
    manager.command(collect_proxy)
  File "/Users/tom/miniconda3/envs/asclepias/lib/python2.7/site-packages/flask_script/__init__.py", line 285, in command
    command = Command(func)
  File "/Users/tom/miniconda3/envs/asclepias/lib/python2.7/site-packages/flask_script/commands.py", line 118, in __init__
    args, varargs, keywords, defaults = inspect.getargspec(func)
  File "/Users/tom/miniconda3/envs/asclepias/lib/python2.7/inspect.py", line 815, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <LocalProxy unbound> is not a Python function
```

Here is the output of ``pip freeze`` so that you can see the various version numbers:

```
$ pip freeze
alabaster==0.7.10
alembic==0.6.7
amqp==2.1.4
aniso8601==1.2.1
appdirs==1.4.3
asn1crypto==0.22.0
Babel==2.4.0
backports.lzma==0.0.8
bagit==1.5.4
BeautifulSoup==3.2.1
beautifulsoup4==4.6.0
billiard==3.5.0.2
blinker==1.4
celery==4.0.2
Cerberus==0.7
certifi==2017.4.17
cffi==1.10.0
chardet==3.0.4
click==6.7
configobj==5.0.6
contextlib2==0.5.5
cryptography==1.9
datacite==0.3.0
decorator==4.0.11
dictdiffer==0.6.1
docutils==0.13.1
elasticsearch==5.4.0
enum34==1.1.6
feedparser==5.2.1
fixture==1.5.9
Flask==0.12.2
Flask-Admin==1.5.0
Flask-Assets==0.12
Flask-Babel==0.11.2
Flask-Breadcrumbs==0.4.0
Flask-Cache==0.13.1
Flask-Collect==1.3.2
Flask-Email==1.4.4
Flask-Gravatar==0.4.2
Flask-IIIF==0.2.1
Flask-Login==0.4.0
Flask-Menu==0.5.1
Flask-OAuthlib==0.6.0
Flask-Principal==0.4.0
Flask-Registry==0.2.0
Flask-RESTful==0.3.6
Flask-Script==2.0.5
Flask-SQLAlchemy==2.2
Flask-WTF==0.14.2
fs==2.0.3
functools32==3.2.3.post2
future==0.16.0
html5lib==0.999999999
idna==2.5
imagesize==0.7.1
infinity==1.4
intbitset==2.3.0
intervals==0.8.0
invenio==2.1.1
invenio-base==0.3.1
invenio-celery==0.1.1
invenio-client==0.1.0
invenio-ext==0.3.2
invenio-query-parser==0.6.0
invenio-utils==0.2.0
ipaddress==1.0.18
isodate==0.5.4
itsdangerous==0.24
jellyfish==0.5.6
Jinja2==2.9.6
jsonschema==2.6.0
kombu==4.0.2
libmagic==1.0
lxml==3.8.0
Mako==1.0.6
MarkupSafe==1.0
mechanize==0.3.3
mistune==0.7.4
msgpack-python==0.4.8
MySQL-python==1.2.5
numpy==1.13.0
nydus==0.11.0
oauthlib==0.7.2
ordereddict==1.1
passlib==1.7.1
Pillow==2.9.0
pycparser==2.17
Pygments==2.2.0
PyLD==0.7.2
pyparsing==2.0.1
pyPdf==1.13
PyPDF2==1.26.0
pyPEG2==2.15.2
pyrtlsdr==0.2.3
PyStemmer==1.3.0
python-dateutil==2.6.0
python-magic==0.4.13
python-twitter==3.3
pytz==2017.2
PyYAML==3.12
rauth==0.7.3
raven==6.1.0
rdflib==4.2.2
redis==2.10.5
reportlab==3.1.44
requests==2.17.3
requests-oauthlib==0.8.0
scandir==1.5
selenium==3.4.3
six==1.10.0
snowballstemmer==1.2.1
speaklater==1.3
Sphinx==1.6.2
sphinxcontrib-websupport==1.0.1
splinter==0.7.5
SQLAlchemy==1.1.10
SQLAlchemy-Utils==0.32.14
Test-Invenio-Overlay==0.1.dev0
typing==3.6.1
Unidecode==0.4.20
urllib3==1.21.1
validators==0.12.0
vine==1.1.3
webassets==0.12.1
webencodings==0.5.1
Werkzeug==0.12.2
workflow==1.2.0
WTForms==2.1
WTForms-Alchemy==0.16.2
WTForms-Components==0.10.3
WTForms-SQLAlchemy==0.1
```

**Comment by astrofrog** [comment]
The error disappears if I downgrade flask-collect to 1.2.2

**Comment by aigentic-net** [comment]
## Triage note (March 2026)

This issue targets **Invenio v2** (the traceback shows Python 2.7, `invenio==2.1.1`, `Flask-Script`, and `Flask-Collect`). All of these components are end-of-life:

- `inveniomanage` was the v2 CLI, replaced by the `invenio` CLI (via Flask/Click) in Invenio v3
- `Flask-Script` is deprecated and not used in v3+
- `Flask-Collect` is not a dependency of modern Invenio
- Python 2.7 reached EOL in January 2020

Invenio v2 has not been maintained for years and is not receiving fixes.

**Recommendation:** Close as obsolete. Users encountering CLI issues on Invenio v3+ should file new issues against the relevant module (e.g. `invenio-app`, `invenio-base`).
