### ISSUE TITLE
tests: fully test the bootstrap3 theme with Invenio v3.4

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio#4061]
The old bootstrap3 theme should be fully tested with Invenio v3.4 to make sure it still works.

1. Boostrap a new cookiecutter-invenio-instance
2. Change ``APP_THEME`` config to ``APP_THEME = ['bootstrap3']`` (this should enable the bootstrap3 theme).
3. Compare each page with the semantic-ui theme and bootstrap3 theme.

**Comment by lnielsen** [comment]
Front-page is broken:

```
Traceback (most recent call last):
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/werkzeug/middleware/dispatcher.py", line 66, in __call__
    return app(environ, start_response)
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/invenio_theme/views.py", line 25, in index
    current_app.config['THEME_FRONTPAGE_TEMPLATE'],
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/lnielsen/.virtualenvs/test-site-6sgDrUfX/lib/python3.6/site-packages/invenio_app/helpers.py", line 99, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: test_site/frontpage.html
```

**Comment by topless** [comment]
![Screenshot 2020-12-08 at 1 48 10 PM](https://user-images.githubusercontent.com/230805/101485977-43ab3400-395c-11eb-86a7-97ae5156572f.png)

Thanks to @ntarocco for the help and input. 
This is the current state of the search result. There are two issues going on.

1) The title of the record is not displayed. This is because the template is trying to render `record.metadata.title_statement.title` while in our record we have `record.metadata.title`.
    - We can possibly override `SEARCH_UI_JSTEMPLATE_RESULTS` in the cookie cutter and provide a template that works.
    - Release invenio-search-ui with templates representing the latest record model.

2) The `Sort by` dropdown works only for the `most recent` option, there seems to be an issue with `bestmatch` prefixed with `-` and angular, which we haven't figured out yet.
