### ISSUE TITLE
ELIFECYCLE error code

### ISSUE THREAD

**Issue by espenfl** [inveniosoftware/invenio#4082]
Package version (if known): 3.4

## Describe the bug
Upon starting from a fresh Centos 8.2, installing python 3.8 using alt install, enabling a virtualenv for python 3.8 and following https://inveniosoftware.org/products/framework/ we get after `./scripts/bootstrap`:

```
(invenio) [espenfl@invenio my-site]$ more /home/espenfl/.npm/_logs/2021-01-08T12_26_47_788Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run-script', 'build' ]
2 info using npm@6.14.9
3 info using node@v10.21.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle invenio-assets@1.0.0~prebuild: invenio-assets@1.0.0
6 info lifecycle invenio-assets@1.0.0~build: invenio-assets@1.0.0
7 verbose lifecycle invenio-assets@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle invenio-assets@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/espenfl/
env/invenio/var/instance/assets/node_modules/.bin:/home/espenfl/env/invenio/bin:/home/espenfl/env/invenio/bin:/home/espenfl/.local/bin:/home
/espenfl/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
9 verbose lifecycle invenio-assets@1.0.0~build: CWD: /home/espenfl/env/invenio/var/instance/assets
10 silly lifecycle invenio-assets@1.0.0~build: Args: [ '-c',
10 silly lifecycle   'NODE_PRESERVE_SYMLINKS=1 NODE_ENV=production webpack --config ./build/webpack.config.js' ]
11 silly lifecycle invenio-assets@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle invenio-assets@1.0.0~build: Failed to exec build script
13 verbose stack Error: invenio-assets@1.0.0 build: `NODE_PRESERVE_SYMLINKS=1 NODE_ENV=production webpack --config ./build/webpack.config.js
`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid invenio-assets@1.0.0
15 verbose cwd /home/espenfl/env/invenio/var/instance/assets
16 verbose Linux 4.18.0-193.19.1.el8_2.x86_64
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run-script" "build"
18 verbose node v10.21.0
19 verbose npm  v6.14.9
20 error code ELIFECYCLE
21 error errno 1
22 error invenio-assets@1.0.0 build: `NODE_PRESERVE_SYMLINKS=1 NODE_ENV=production webpack --config ./build/webpack.config.js`
22 error Exit status 1
23 error Failed at the invenio-assets@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
## Steps to Reproduce
Upon starting from a fresh Centos 8.2, installing python 3.8 using alt install, enabling a virtualenv for python 3.8 and following https://inveniosoftware.org/products/framework/.

**Comment by ppanero** [comment]
@espenfl I see you have node 10:

```
2 info using npm@6.14.9
3 info using node@v10.21.0
```

For the latest invenio 3.4 you need node 14+

I have opened an issue to update that... https://github.com/inveniosoftware/training/issues/106

**Comment by espenfl** [comment]
@ppanero Great. Thanks a lot.

**Comment by ppanero** [comment]
@espenfl feel free to re-open this issue if still persist after that :) sorry for the inconvenience
