### ISSUE TITLE
BibUpload: Cannot bibupload file containing UTF-8 chars

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#559]
Originally by _[grfavre (@gfavre)](https://github.com/gfavre)_ on 2011-03-17

When trying to bibupload -r the attached file, the task crashed on first record. Looking at invenio.err, I found a UnicodeError.

I tried this using 4suite and pyRXP. Current setting is 
`CFG_BIBRECORD_PARSERS_AVAILABLE = ['pyrxp', '4suite', 'minidom']`

```
>>> Traceback details

Traceback (most recent call last):
  File "/var/www/infoscience.epfl.ch/private/infoscience-env/lib/python2.6/site-packages/invenio/bibtask.py", line 754, in _task_run
    if callable(task_run_fnc) and task_run_fnc():
  File "/var/www/infoscience.epfl.ch/private/infoscience-env/lib/python2.6/site-packages/invenio/bibupload.py", line 1987, in task_run_core
    pretend=task_get_option('pretend'))
  File "/var/www/infoscience.epfl.ch/private/infoscience-env/lib/python2.6/site-packages/invenio/bibupload.py", line 343, in bibupload
    rec_xml_new = record_xml_output(record)
  File "/var/www/infoscience.epfl.ch/private/infoscience-env/lib/python2.6/site-packages/invenio/bibrecord.py", line 899, in record_xml_output
    return '\n'.join(marcxml)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 80: ordinal not in range(128)
Locals by frame, innermost last
```

The file is UTF-8-encoded, contains accentuated chars on the second record (see line 87).

**Comment by kaplun** [comment]
Closing this, since workaround exists.
