### ISSUE TITLE
install selenium module on build hosts

### ISSUE THREAD

**Issue by jrbl** [inveniosoftware/invenio#837]
Originally on 2011-10-29

Invenio's build status is failed at least in part because the build host doesn't have the 'selenium' module used by the unit test library, so we get these:
```
Traceback (most recent call last):
  File "/opt/invenio/bin/inveniocfg", line 33, in <module>
    main()
  File "/usr/local/lib/python2.6/dist-packages/invenio/inveniocfg.py", line 1241, in main
    cli_cmd_run_unit_tests(conf)
  File "/usr/local/lib/python2.6/dist-packages/invenio/inveniocfg.py", line 735, in cli_cmd_run_unit_tests
    from invenio.testutils import build_and_run_unit_test_suite
  File "/usr/local/lib/python2.6/dist-packages/invenio/testutils.py", line 35, in <module>
    from selenium import webdriver
ImportError: No module named selenium
```

**Comment by jirikuncar** [comment]
Invenio 3 packages can optionally enable Selenium testing as shown in Invenio-Account E2E test configuration https://github.com/inveniosoftware/invenio-accounts/blob/master/tests/e2e/conftest.py
